# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
