# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160320_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.Project'),
        ),
    ]
