# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160329_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application',
            field=models.ManyToManyField(blank=True, to='project.Application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pipeline',
            field=models.ManyToManyField(blank=True, to='project.Pipeline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='strategy',
            field=models.ManyToManyField(blank=True, to='project.Strategy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, to='project.Technology'),
        ),
    ]
