# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160426_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='version',
            field=models.IntegerField(blank=True),
        ),
    ]
