# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='anticipated_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='application',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goals_to_scale',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started',
        ),
        migrations.RemoveField(
            model_name='project',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Coverage',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='coverageversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
