# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20160502_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageversion',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
