# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_partnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlogo',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
