# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160428_0952'),
        ('project', '0013_auto_20160507_1554'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='team', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='user.UserProfile'),
        ),
    ]
