# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 09:28
from __future__ import unicode_literals

from django.db import migrations
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20160601_0859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', project.models.ProjectManager()),
            ],
        ),
    ]
