# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20160603_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_id',
            field=models.CharField(default='', help_text='<CountryCode>-<uuid>-x-<ProjectID> eg: HU9fa42491x1', max_length=64),
        ),
    ]
