# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-14 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_project_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlogo',
            name='project',
        ),
        migrations.DeleteModel(
            name='PartnerLogo',
        ),
    ]
