# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_convert_static_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthFocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('health_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_focus_areas', to='project.HealthCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
