# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 18:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160719_1259'),
        ('project', '0023_auto_20171119_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved', models.NullBooleanField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='digitalstrategy',
            options={'verbose_name_plural': 'Digital Strategies'},
        ),
        migrations.AddField(
            model_name='project',
            name='draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='project.Project'),
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
