# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 10:43
from __future__ import unicode_literals

from django.db import migrations

digital_strategies = [
    {
        "name": "Client",
        "subGroups": [
            {'name': 'Targeted client communication',
             'strategies': [
                 'Transmit health event alerts to specific population group(s)',
                 'Transmit targeted health information to client based on health status or demographics',
                 'Transmit targeted alerts and reminders to client(s)',
                 'Transmit diagnostics result, or availability of result, to clients',
             ]},
            {'name': 'Untargeted client communication',
             'strategies': [
                 'Transmit untargeted health information to an undefined population',
                 'Transmit untargeted health event alerts to undefined group.',
             ]},
            {'name': 'Client to client communication',
             'strategies': [
                 'Peer group for clients',
             ]},
            {'name': 'Personal health tracking',
             'strategies': [
                 'Access by client to own medical records',
                 'Self monitoring of health or diagnostic data by client',
                 'Active data capture/documentation by client',
             ]},
            {'name': 'Citizen based reporting',
             'strategies': [
                 'Reporting of health system feedback by clients',
                 'Reporting of public health events by clients',
             ]},
            {'name': 'On demand information services to clients',
             'strategies': [
                 'Client look-up of health information',
             ]},
            {'name': 'Client financial transactions',
             'strategies': [
                 'Transmit or manage out of pocket payments by client',
                 'Transmit or manage vouchers to client for health services',
                 'Transmit or manage incentives to clients for health services',
             ]},
        ]
    },
    {
        "name": "Provider",
        "subGroups": [
            {'name': 'Client identification and registration',
             'strategies': [
                 'Verify client unique identity',
                 'Enrol client for health services/clinical care plan',
             ]},
            {'name': 'Client health records',
             'strategies': [
                 "Longitudinal tracking of client's health status and services received",
                 "Manage client's structured clinical records",
                 "Manage client's unstructured clinical records (e.g. notes, images, documents)",
                 "Routine health indicator data collection and management",
             ]},
            {'name': 'Healthcare provider decision support',
             'strategies': [
                 'Provide prompts and alerts based according to protocol',
                 'Provide checklist according to protocol',
                 'Screen clients by risk or other health status',
             ]},
            {'name': 'Telemedicine',
             'strategies': [
                 'Consultations between remote client and healthcare provider',
                 'Remote monitoring of client health or diagnostic data by provider',
                 'Transmission of medical data (e.g. images, notes, and videos) to healtcare provider',
                 'Consultations for case management between healthcare providers',
             ]},
            {'name': 'Healthcare provider communication',
             'strategies': [
                 'Communication from healthcare provider to supervisor',
                 'Communication and performance feedback to healthcare provider',
                 'Transmit routine news and workflow notifications to healthcare provider (s)',
                 'Transmit non-routine health event alerts to healthcare providers',
                 'Peer group for healthcare providers',
             ]},
            {'name': 'Referral coordination',
             'strategies': [
                 'Coordinate emergency response and transport',
                 'Manage referrals between points of service within health sector',
                 'Manage referrals between health and other sectors (social services, police, justice, economic support schemes)',
             ]},
            {'name': 'Scheduling and activity planning for healthcare providers',
             'strategies': [
                 'Schedule client appointments based on clinical care plan',
                 "Schedule healthcare provider's activities",
             ]},
            {'name': 'Healthcare provider training',
             'strategies': [
                 'Provide training content and reference material to healthcare provider(s)',
                 'Assess capacity of healthcare provider',
             ]},
            {'name': 'Prescription and medication management',
             'strategies': [
                 'Transmit or track prescription orders',
                 "Track client's medication consumption",
                 'Report adverse drug effects',
             ]},
            {'name': 'Laboratory and diagnostics imaging management',
             'strategies': [
                 'Transmit client diagnostic result to healthcare provider',
                 'Transmit and track diagnostic orders',
                 'Capture diagnostic results from digital devices',
                 'Track biological specimens',
             ]}
        ]
    },
    {
        "name": "System",
        "subGroups": [
            {'name': 'Human resource management',
             'strategies': [
                 'List health workforce cadres and related identification information',
                 'Monitor performance of healthcare provider(s)',
                 'Manage registration/certification of healthcare provider(s)',
                 'Record training information on healthcare provider(s)',
             ]},
            {'name': 'Supply chain management',
             'strategies': [
                 'Manage inventory and distribution of health commodities',
                 'Notify stock levels of health commodities',
                 'Monitor cold-chain sensitive commodities',
                 'Register licensed drugs and health commodities',
                 'Manage procurement of commodities',
                 'Report counterfeit or substandard drugs by clients',
             ]},
            {'name': 'Public health event notification',
             'strategies': [
                 'Notification of public health events from point of diagnosis',
             ]},
            {'name': 'Civil Registration and Vital Statistics (CRVS)',
             'strategies': [
                 'Notify birth event',
                 'Register birth event',
                 'Certify birth event',
                 'Notify death event',
                 'Register death event',
                 'Certify death event',
             ]},
            {'name': 'Health financing',
             'strategies': [
                 'Register and verify client insurance membership',
                 'Track insurance billing and claims submission',
                 'Track and manage insurance reimbursement',
                 'Transmit or manage routine payroll payment to healthcare provider(s)',
                 'Transmit or manage incentives to healthcare provider (s)',
                 'Manage budget and expenditures',
             ]},
            {'name': 'Equipment and asset management',
             'strategies': [
                 'Monitor status and maintenance of health equipment',
                 'Track regulation and licensing of medical equipment',
             ]},
            {'name': 'Facility management',
             'strategies': [
                 'List health facilities and related information',
                 'Assess health facilities',
             ]}
        ]
    },
    {
        "name": "Data service",
        "subGroups": [
            {'name': 'Data collection, management, and use',
             'strategies': [
                 'Non routine data collection and management',
                 'Data storage and aggregation',
                 'Data synthesis and visualizations',
                 'Automated analysis of data to generate new information or predictions on future events',
             ]},
            {'name': 'Data coding',
             'strategies': [
                 'Parse unstructured data into structured data',
                 'Merge, de-duplicate and curate coded datasets or terminologies',
                 'Classify disease codes',
             ]},
            {'name': 'Location mapping',
             'strategies': [
                 'Map location of health facilities/structures',
                 'Map location of health event',
                 'Map location of clients and households',
                 'Map location of healthcare provider(s)',
             ]},
            {'name': 'Data exchange and interoperability',
             'strategies': [
                 'Date exchange across systems',
             ]}
        ]
    }
]


def create_new_digital_stategies(apps, schema_editor):
    DigitalStrategy = apps.get_model('project', 'DigitalStrategy')

    DigitalStrategy.all_objects.all().delete()

    for group in digital_strategies:
        for parent in group['subGroups']:
            item = DigitalStrategy.all_objects.create(group=group['name'], name=parent['name'])
            for strat in parent['strategies']:
                DigitalStrategy.all_objects.create(group=group['name'], name=strat, parent=item)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_convert_static_dynamic'),
    ]

    operations = [
        migrations.RunPython(create_new_digital_stategies)
    ]
