# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_update_digital_strategies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcategory',
            options={'verbose_name_plural': 'Health Categories'},
        ),
        migrations.AlterModelManagers(
            name='healthcategory',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='healthfocusarea',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='digitalstrategy',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='interoperabilitylink',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='technologyplatform',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
