# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20171129_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='digitalstrategy',
            options={'ordering': ['name'], 'verbose_name_plural': 'Digital Strategies'},
        ),
        migrations.AlterModelOptions(
            name='healthcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Health Categories'},
        ),
        migrations.AlterModelOptions(
            name='healthfocusarea',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hisbucket',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hscchallenge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='interoperabilitylink',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='interoperabilitystandard',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='technologyplatform',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='application',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='digitalstrategy',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='healthcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='healthfocusarea',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='hisbucket',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='hscchallenge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='interoperabilitylink',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='interoperabilitystandard',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='licence',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='technologyplatform',
            managers=[
            ],
        ),
    ]
