# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20171129_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
