# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_delete_application'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hscchallenge',
            managers=[
            ],
        ),
    ]
