# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20171201_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalstrategy',
            name='group',
            field=models.CharField(choices=[('Client', 'Client'), ('Provider', 'Provider'), ('System', 'System'), ('Data service', 'Data service')], max_length=255),
        ),
    ]
