# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20171201_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscchallenge',
            options={'ordering': ['name', 'challenge'], 'verbose_name_plural': 'Health System Challenges'},
        ),
    ]
