# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20171211_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalstrategy',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='digitalstrategy',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='digitalstrategy',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='digitalstrategy',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hisbucket',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hisbucket',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hisbucket',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hisbucket',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='challenge_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='challenge_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='challenge_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='challenge_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='pre_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='pre_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='pre_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='pre_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
