# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 13:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.expressions import F


def copy_translations(apps, schema_editor):
    DigitalStrategy = apps.get_model('project', 'DigitalStrategy')
    HSCChallenge = apps.get_model('project', 'HSCChallenge')
    HealthCategory = apps.get_model('project', 'HealthCategory')
    HealthFocusArea = apps.get_model('project', 'HealthFocusArea')
    InteroperabilityLink = apps.get_model('project', 'InteroperabilityLink')
    TechnologyPlatform = apps.get_model('project', 'TechnologyPlatform')
    Licence = apps.get_model('project', 'Licence')
    InteroperabilityStandard = apps.get_model('project', 'InteroperabilityStandard')
    HISBucket = apps.get_model('project', 'HISBucket')

    DigitalStrategy.all_objects.update(name_en=F('name'))
    HSCChallenge.objects.update(name_en=F('name'), challenge_en=F('challenge'))
    HealthCategory.all_objects.update(name_en=F('name'))
    HealthFocusArea.all_objects.update(name_en=F('name'))
    InteroperabilityLink.all_objects.update(name_en=F('name'), pre_en=F('pre'))
    TechnologyPlatform.all_objects.update(name_en=F('name'))
    Licence.all_objects.update(name_en=F('name'))
    InteroperabilityStandard.all_objects.update(name_en=F('name'))
    HISBucket.all_objects.update(name_en=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20171212_1331'),
    ]

    operations = [
        migrations.RunPython(copy_translations, migrations.RunPython.noop)
    ]
