# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20171212_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Health System Challenge Group',
            },
            bases=(project.models.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='hscchallenge',
            options={'ordering': ['name', 'challenge'], 'verbose_name': 'Health System Challenge', 'verbose_name_plural': 'Health System Challenges'},
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='project.HSCGroup'),
        ),
    ]
