# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20171220_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscchallenge',
            options={'verbose_name': 'Health System Challenge', 'verbose_name_plural': 'Health System Challenges'},
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='challenge_en',
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='challenge_es',
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='challenge_fr',
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='challenge_pt',
        ),
        migrations.AddField(
            model_name='hscgroup',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscgroup',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscgroup',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscgroup',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='hscchallenge',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='project.HSCGroup'),
        ),
    ]
