# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-03 08:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_auto_20180222_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='odk_etag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='odk_extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='odk_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
