# Generated by Django 2.1 on 2018-08-29 13:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_django2_20180711_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='odk_extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
