# Generated by Django 2.1 on 2018-10-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_historicalprojectapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectapproval',
            name='project',
        ),
    ]
