# Generated by Django 2.1 on 2018-10-01 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_remove_historicalprojectapproval_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectapproval',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
