# Generated by Django 2.1 on 2019-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_auto_20181203_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalstrategy',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthcategory',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='healthfocusarea',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hisbucket',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscchallenge',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hscgroup',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitylink',
            name='pre_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
