# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 11:38
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

PT_TRANSLATIONS = [
    '2018_01_30__tp_pt.json',
    '2018_01_30__licence_pt.json',
    '2018_01_30__istandard_pt.json',
    '2018_01_30__ilink_pt.json',
    '2018_01_30__his_pt.json',
    '2018_01_30__hfa_pt.json',
    '2018_01_30__hscgroup_pt.json',
    '2018_01_30__hc_pt.json',
    '2018_01_30__ds_pt.json',
    '2018_01_30__hscchallange_pt.json'
]


def load_fixture(apps, schema_editor):
    for fixture in PT_TRANSLATIONS:
        call_command('loaddata', fixture)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_auto_20190205_1052')
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
