# Generated by Django 2.1 on 2019-02-17 23:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_auto_20190217_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimportv2',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country'),
        ),
        migrations.AlterField(
            model_name='projectimportv2',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Donor'),
        ),
        migrations.AlterField(
            model_name='projectimportv2',
            name='header_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
