# Generated by Django 2.1 on 2019-03-06 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20190217_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='original_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
