# Generated by Django 2.1 on 2019-06-19 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project.cache


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_importrow_original_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNICEFCapabilityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'UNICEF Capability Categories',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UNICEFCapabilityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'UNICEF Capability Levels',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UNICEFCapabilitySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'UNICEF Capability Sub Categories',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UNICEFGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('capability_level_question', models.CharField(blank=True, max_length=512)),
                ('capability_category_question', models.CharField(blank=True, max_length=512)),
                ('capability_subcategory_question', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name_plural': 'UNICEF Goal Areas',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UNICEFResultArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('goal_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_areas', to='project.UNICEFGoal')),
            ],
            options={
                'verbose_name_plural': 'UNICEF Result Areas',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='unicefcapabilitysubcategory',
            name='goal_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_subcategories', to='project.UNICEFGoal'),
        ),
        migrations.AddField(
            model_name='unicefcapabilitylevel',
            name='goal_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_levels', to='project.UNICEFGoal'),
        ),
        migrations.AddField(
            model_name='unicefcapabilitycategory',
            name='goal_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_categories', to='project.UNICEFGoal'),
        ),
    ]
