# Generated by Django 2.1 on 2019-06-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20190619_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicefgoal',
            name='capability_category_question',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='unicefgoal',
            name='capability_level_question',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='unicefgoal',
            name='capability_subcategory_question',
            field=models.CharField(max_length=512),
        ),
    ]
