# Generated by Django 2.1 on 2019-06-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_auto_20190619_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalstrategy',
            options={'ordering': ['group', 'name'], 'verbose_name': 'WHO Digital Health Intervention (DHI)', 'verbose_name_plural': 'WHO Digital Health Interventions (=UNICEF Health Capability Categories)'},
        ),
    ]
