# Generated by Django 2.1 on 2020-09-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_global_portfolio_owner'),
        ('project', '0068_projectimportv2_country_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=511)),
                ('icon', models.CharField(blank=True, max_length=1)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('ACT', 'Active'), ('ARC', 'Archived')], default='DR', max_length=3)),
                ('managers', models.ManyToManyField(blank=True, related_name='portfolios', to='user.UserProfile')),
                ('projects', models.ManyToManyField(blank=True, related_name='portfolios', to='project.Project')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=511)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='project.Portfolio')),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
    ]
