# Generated by Django 2.1 on 2020-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_portfolio_problemstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='icon',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
