# Generated by Django 2.1 on 2020-09-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_auto_20200908_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemstatement',
            options={'default_manager_name': 'objects', 'ordering': ['name']},
        ),
    ]
