# Generated by Django 2.1 on 2020-09-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_global_portfolio_owner'),
        ('project', '0071_auto_20200908_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPortfolioState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rnci', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ratp', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ra', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ee', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('nst', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('nc', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ps', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('psa_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rnci_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ratp_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ra_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ee_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('nst_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('nc_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('impact', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rnci', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ratp', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ra', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ee', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('nst', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('nc', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('ps', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('psa_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rnci_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ratp_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ra_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ee_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('nst_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('nc_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('portfolio_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to='project.ProjectPortfolioState')),
                ('psa', models.ManyToManyField(blank=True, to='project.ProblemStatement')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to='user.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ScalePhase',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('scale', models.IntegerField(choices=[(1, 'Ideation'), (2, 'Research & Development'), (3, 'Proof of Concept'), (4, 'Transition to Scale'), (5, 'Scaling'), (6, 'Sustainable Scale')], primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='project.Portfolio'),
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='project.Project'),
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='psa',
            field=models.ManyToManyField(blank=True, to='project.ProblemStatement'),
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='scale_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ScalePhase'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewscore',
            unique_together={('reviewer', 'portfolio_review')},
        ),
        migrations.AlterUniqueTogether(
            name='projectportfoliostate',
            unique_together={('portfolio', 'project')},
        ),
    ]
