# Generated by Django 2.1 on 2020-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_auto_20200915_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectportfoliostate',
            name='complete',
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
