# Generated by Django 2.1 on 2020-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_auto_20200928_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfoliostate',
            name='impact',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='projectportfoliostate',
            name='scale_phase',
            field=models.IntegerField(blank=True, choices=[(1, 'Ideation'), (2, 'Research & Development'), (3, 'Proof of Concept'), (4, 'Transition to Scale'), (5, 'Scaling'), (6, 'Sustainable Scale')], null=True),
        ),
        migrations.DeleteModel(
            name='ScalePhase',
        ),
    ]
