# Generated by Django 2.1 on 2020-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_auto_20201001_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfoliostate',
            name='scale_phase',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Ideation'), (2, '2 - Research & Development'), (3, '3 - Proof of Concept'), (4, '4 - Transition to Scale'), (5, '5 - Scaling'), (6, '6 - Sustainable Scale')], null=True),
        ),
    ]
