# Generated by Django 2.1 on 2020-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_global_portfolio_owner'),
        ('project', '0077_auto_20201012_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_projects', to='user.UserProfile'),
        ),
    ]
