# Generated by Django 2.1 on 2020-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0079_auto_20201026_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatement',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
