# Generated by Django 2.1 on 2020-12-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userprofile_filters'),
        ('project', '0082_innovationway_isc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyplatform',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='state',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Declined')], default=1),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='state',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Declined')], default=1),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Declined')], default=1),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='state',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Declined')], default=1),
        ),
    ]
