# Generated by Django 2.1 on 2020-12-08 14:38

from django.db import migrations, models
import django.db.models.manager
import project.cache


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0083_auto_20201207_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
