# Generated by Django 2.1 on 2020-12-11 14:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0084_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISBucket',
        ),
        migrations.DeleteModel(
            name='InteroperabilityLink',
        ),
        migrations.DeleteModel(
            name='InteroperabilityStandard',
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Phase of initiative', 'verbose_name_plural': 'Phases of initiative'},
        ),
        migrations.AlterModelManagers(
            name='hardwareplatform',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='nontechplatform',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='platformfunction',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='hardwareplatform',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='name_ar',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='name_es',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='name_fr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='name_pt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_ar',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_pt',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
