# Generated by Django 2.1 on 2020-12-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0086_reload_data_rebuild_search_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
