# Generated by Django 2.1 on 2020-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0086_reload_data_rebuild_search_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['name'], 'verbose_name_plural': '[DEPRECATED] Phase of Initiative'},
        ),
    ]
