# Generated by Django 2.1 on 2021-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0090_reviewscore_remove_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectportfoliostate',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='reviewscore',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='projectportfoliostate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
