# Generated by Django 2.1 on 2021-09-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0092_auto_20210723_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='odk_etag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='odk_extra_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='odk_id',
        ),
    ]
