# Generated by Django 2.1 on 2021-09-02 09:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_project_initial_versions(apps, schema_editor):
        Project = apps.get_model('project', 'Project')
        ProjectVersion = apps.get_model('project', 'ProjectVersion')

        for project in Project.objects.all():
            data = project.data if project.public_id else project.draft
            user = project.team.first() if project.team.count() > 0 else None
            ProjectVersion.objects.create(project=project, data=data,
                                          name=project.name,
                                          user=user,
                                          published=True if project.public_id else False)

    dependencies = [
        ('user', '0029_remove_userprofile_odk_sync'),
        ('project', '0093_auto_20210901_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='project.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_versions', to='user.UserProfile')),
            ],
            options={
                'ordering': ['modified'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectversion',
            unique_together={('project', 'version')},
        ),
        migrations.RunPython(create_project_initial_versions, migrations.RunPython.noop),
    ]
