# Generated by Django 2.1 on 2021-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0094_project_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
