# Generated by Django 2.1 on 2021-09-15 14:31

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0095_auto_20210908_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='source_images'),
        ),
    ]
