# Generated by Django 2.1 on 2022-01-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0096_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverageversion',
            name='project',
        ),
        migrations.DeleteModel(
            name='CoverageVersion',
        ),
    ]
