# Generated by Django 2.1 on 2022-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0097_auto_20220127_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalstrategy',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='hardwareplatform',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='healthcategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='healthfocusarea',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='hscchallenge',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='hscgroup',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='nontechplatform',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='platformfunction',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='technologyplatform',
            name='name_ar',
        ),
    ]
