# Generated by Django 2.1 on 2022-03-01 15:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0055_auto_20220214_1500'),
        ('project', '0098_auto_20220214_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LACR'), (4, 'MENA'), (5, 'SAR'), (6, 'WCAR'), (7, 'HQ')]), size=None)),
                ('phase', models.IntegerField(choices=[(0, 'Pilot'), (1, 'Acceleration'), (2, 'Scale')])),
                ('people_reached', models.PositiveIntegerField()),
                ('open_source_frontier_tech', models.BooleanField()),
                ('learning_investment', models.BooleanField()),
                ('countries', models.ManyToManyField(to='country.Country')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='innovation_hub',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_to_date',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='portfolios',
            field=models.ManyToManyField(related_name='solutions', to='project.Portfolio'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem_statements',
            field=models.ManyToManyField(to='project.ProblemStatement'),
        ),
    ]
