# Generated by Django 2.1 on 2022-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0099_auto_20220303_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='people_reached_override',
            field=models.PositiveIntegerField(blank=True, help_text='Override country based calculation', null=True),
        ),
    ]
