# Generated by Django 2.1 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0100_solution_people_reached_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='innovation_hub',
            field=models.BooleanField(default=False),
        ),
    ]
