# Generated by Django 2.1 on 2022-03-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0101_auto_20220321_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='landscape_review',
            field=models.BooleanField(default=False),
        ),
    ]
