# Generated by Django 2.1 on 2023-06-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0103_auto_20230511_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
