# Generated by Django 2.1 on 2023-07-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0104_deltalink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeltaLink',
        ),
    ]
