# Generated by Django 2.1 on 2023-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0105_delete_deltalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='completion_marks_an_initiative_as_inactive',
            field=models.BooleanField(
                default=False, help_text='When this phase is marked as completed (with an end date) it means that the initiative is no longer active.<br>It will not move automatically to a following phase, but will stay in this phase.'),
        ),
    ]
