# Generated by Django 2.1 on 2023-07-20 18:43
from django.core.management import call_command
from django.db import migrations


def rebuild_search(apps, schema_editor):
    call_command('rebuild_search')


def reorder_stages(apps, schema_editor):
    Stage = apps.get_model('project', 'Stage')
    order = 0
    for item in Stage.objects.all():
        order += 1
        item.order = order
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0106_stage_completion_marks_an_initiative_as_inactive'),
    ]

    operations = [
        # migrations.RunPython(rebuild_search, reverse_code=migrations.RunPython.noop),
        # migrations.RunPython(reorder_stages, reverse_code=migrations.RunPython.noop),
    ]
