# Generated by Django 2.1 on 2023-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0107_reorder_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
