# Generated by Django 2.1 on 2023-08-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0107_stage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareplatform',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='nontechplatform',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='platformfunction',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='technologyplatform',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
