# Generated by Django 2.1 on 2023-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0109_reorder_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='portfolios',
            field=models.ManyToManyField(blank=True, related_name='solutions', to='project.Portfolio'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem_statements',
            field=models.ManyToManyField(blank=True, to='project.ProblemStatement'),
        ),
    ]
