# Generated by Django 2.1 on 2023-08-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0110_auto_20230823_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareplatform',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardaware_tags', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='nontechplatform',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nontechnology_tags', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='platformfunction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_tags', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='technologyplatform',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_tags', to='project.Project'),
        ),
    ]
