# Generated by Django 2.1 on 2023-07-20 18:43
from django.core.management import call_command
from django.db import migrations


def add_taxonomies(apps, schema_editor):
    call_command('add_taxonomies', '--verbosity', 0)


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0110_auto_20230823_1021'),
    ]

    operations = [
        migrations.RunPython(
            add_taxonomies, reverse_code=migrations.RunPython.noop),
    ]
