# Generated by Django 4.2.3 on 2023-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0113_alter_historicalprojectapproval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='set_aside_2021',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='set_aside_2022',
            field=models.BooleanField(default=False),
        ),
    ]
