FROM node:12.21.0-alpine
# This is to allow yarn to install from github
RUN apk update && apk upgrade && \
    apk add --no-cache bash

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD frontend/package.json /tmp/
RUN cd /tmp && npm i
RUN cd /usr/src/app && ln -s /tmp/node_modules

COPY frontend/ /usr/src/app/
COPY django/translations/master.pot /usr/src/app/
#RUN echo "NODE_ENV=production" >> .env
RUN npm build --quiet
####
ENV HOST 0.0.0.0
EXPOSE 3000
# start command
CMD npm start
