FROM node:14.21.0-alpine
# This is to allow yarn to install from github
RUN apk update && apk upgrade && \
    apk add --no-cache bash gettext

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY frontend/package.json frontend/yarn.lock ./
RUN yarn --silent --non-interactive

COPY frontend/ ./
COPY django/translations/master.pot ./
#RUN echo "NODE_ENV=production" >> .env
RUN yarn build --quiet
####
ENV HOST 0.0.0.0
EXPOSE 3000
# start command
CMD yarn start
