# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160719_1259'),
        ('country', '0005_load_initial_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='cover_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='footer_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='footer_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.ForeignKey(help_text='User who can update the country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_admin', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='NULL', help_text='ISO3166-1 country code', max_length=4, unique=True),
        ),
    ]
