# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20170314_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Text field'), (2, 'Numeric field'), (3, 'Yes, no field')])),
                ('data', models.TextField(max_length=2000)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
        ),
    ]
