# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_countryfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryfield',
            old_name='data',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='countryfield',
            name='question',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
