# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20170314_1137'),
        ('country', '0010_auto_20170503_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfield',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countryfield',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
