# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_auto_20170505_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='project_approval',
            field=models.BooleanField(default=False),
        ),
    ]
