# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_move_admin_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
    ]
