# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_remove_country_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfield',
            name='draft',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='countryfield',
            name='schema_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.CountryField'),
        ),
        migrations.AlterField(
            model_name='countryfield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Text field'), (2, 'Numeric field'), (3, 'Yes - no field'), (4, 'Single choice'), (5, 'Multiple choice')]),
        ),
    ]
