# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 14:10
from __future__ import unicode_literals

from django.db import migrations


def migrate_country_fields(apps, schema_editor):
    CountryField = apps.get_model('country', 'CountryField')
    for schema in CountryField.objects.filter(schema=True, enabled=True):
        for cf in CountryField.objects.filter(question=schema.question, enabled=True, schema=False):
            cf.schema_instance = schema
            cf.save()

    for cf in CountryField.objects.filter(enabled=True, schema=False):
        cf.draft = cf.answer
        cf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0018_auto_20171206_1402'),
    ]

    operations = [
        migrations.RunPython(migrate_country_fields)
    ]
