# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 13:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_migrate_country_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryfield',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
