# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0020_countryfield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryfield',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='countryfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
