# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0021_auto_20171207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfield',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='country.Country'),
        ),
    ]
