# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_auto_20171211_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
