# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-03 12:53
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.expressions import F


def move_name_to_name_en(apps, schema_editor):
    Country = apps.get_model('country', 'Country')

    Country.objects.update(name_en=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0023_auto_20180103_1129'),
    ]

    operations = [
        migrations.RunPython(move_name_to_name_en, migrations.RunPython.noop),
    ]
