# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0024_auto_20180103_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('id',), 'verbose_name_plural': 'Countries'},
        ),
    ]
