# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0025_country_map_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('map_file', models.FileField(null=True, upload_to='uploaded_maps/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
