# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0025_auto_20180108_1601'),
        ('country', '0028_country_map_activated_on'),
    ]

    operations = [
    ]
