# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0029_merge_20180112_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User who can update the country', related_name='country_admins', to='user.UserProfile'),
        ),
    ]
