# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-21 12:27
from __future__ import unicode_literals

from django.db import migrations


def load_countries(apps, schema_editor):
    Country = apps.get_model("country", "Country")
    country = {
        "model": "country.country",
        "fields": {
            "name": "Lesotho",
            "code": "LS"
        }
    }
    Country.objects.create(name_en=country['fields']['name'], code=country['fields']['code'])


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0030_auto_20180112_0447'),
    ]

    operations = [
        migrations.RunPython(load_countries),
    ]
