# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-22 15:31
from __future__ import unicode_literals

from django.db import migrations


def load_countries(apps, schema_editor):
    Country = apps.get_model("country", "Country")
    countries = [
        {
            "model": "country.country",
            "fields": {
                "name": "Senegal",
                "code": "SN"
            }
        },
        {
            "model": "country.country",
            "fields": {
                "name": "Eritrea",
                "code": "ER"
            }
        },
        {
            "model": "country.country",
            "fields": {
                "name": "Sao Tome & Principe",
                "code": "ST"
            }
        },
        {
            "model": "country.country",
            "fields": {
                "name": "Seychelles",
                "code": "SC"
            }
        }
    ]
    for country in countries:
        Country.objects.create(name=country['fields']['name'], name_en=country['fields']['name'], code=country['fields']['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0031_add_country_lesotho'),
    ]

    operations = [
        migrations.RunPython(load_countries),
    ]
