# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-25 07:06
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone

def add_default_activated(apps, schema_editor):
    Country = apps.get_model('country', 'Country')
    for cf in Country.objects.filter(map_activated_on=None):
        cf.map_activated_on = timezone.now()
        cf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('country', '0032_add_countries_senegal_eritrea_seychelles_saoTome'),
    ]

    operations = [
        migrations.RunPython(add_default_activated)
    ]
