# Generated by Django 2.0.7 on 2018-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0033_default_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User who can update the country', limit_choices_to={'user__groups__name': 'Country Admin'}, related_name='country_admins', to='user.UserProfile'),
        ),
    ]
