# Generated by Django 2.0.7 on 2018-08-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0035_auto_20180808_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_files', to='country.Country'),
        ),
    ]
