# Generated by Django 2.1 on 2018-08-29 13:05

from django.db import migrations

def in_place_migrate_donors(apps, schema_editor):
    Donor = apps.get_model('country', 'Donor')
    Project = apps.get_model('project', 'Project')
    try:
        pp = Project.projects.all()
    except AttributeError:
        pp = Project.objects.all()
    for p in pp:
        if p.data and 'donors' in p.data:
            published_donors = []
            for donor in p.data.get('donors', []):
                obj, _ = Donor.objects.get_or_create(name=donor, name_en=donor)
                published_donors.append(obj.id)
            p.data['donors'] = published_donors
        if p.draft and 'donors' in p.draft:
            draft_donors = []
            for donor in p.draft.get('donors', []):
                obj, _ = Donor.objects.get_or_create(name=donor, name_en=donor)
                draft_donors.append(obj.id)
            p.draft['donors'] = draft_donors
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('country', '0036_auto_20180821_1255'),
    ]

    operations = [
        migrations.RunPython(in_place_migrate_donors)
    ]
