# Generated by Django 2.1 on 2018-09-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0037_migrate_donors_to_objects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('name',), 'verbose_name_plural': 'Donors'},
        ),
        migrations.AddField(
            model_name='donor',
            name='code',
            field=models.CharField(default='NULL', help_text='Acronym for Donor', max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
