# Generated by Django 2.1 on 2018-09-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0039_auto_20180905_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='code',
            field=models.CharField(default='NULL', help_text='Acronym for Donor', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
