# Generated by Django 2.1 on 2018-10-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0042_migrate_country_fields_schema_to_custom_questions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='countrycustomquestion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='donorcustomquestion',
            managers=[
            ],
        ),
    ]
