# Generated by Django 2.1 on 2018-10-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0043_auto_20181009_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfield',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countryfield',
            name='project',
        ),
        migrations.RemoveField(
            model_name='countryfield',
            name='schema_instance',
        ),
        migrations.DeleteModel(
            name='CountryField',
        ),
    ]
