# Generated by Django 2.1 on 2019-06-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0046_auto_20190205_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='unicef_region',
            field=models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LCAR'), (4, 'MENA'), (5, 'ROSA'), (6, 'WCAR'), (7, 'HQ')], null=True),
        ),
        migrations.AddField(
            model_name='fieldoffice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_offices', to='country.Country'),
        ),
    ]
