# Generated by Django 2.1 on 2020-03-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0047_auto_20190619_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('name_fr', models.CharField(max_length=256, null=True)),
                ('name_es', models.CharField(max_length=256, null=True)),
                ('name_pt', models.CharField(max_length=256, null=True)),
                ('name_ar', models.CharField(max_length=256, null=True)),
                ('region', models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LCAR'), (4, 'MENA'), (5, 'ROSA'), (6, 'WCAR'), (7, 'HQ')], null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fieldoffice',
            name='country',
        ),
        migrations.AddField(
            model_name='fieldoffice',
            name='country_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.CountryOffice'),
        ),
    ]
