# Generated by Django 2.1 on 2020-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0050_auto_20200915_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
