# Generated by Django 2.1 on 2020-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0051_auto_20201030_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldoffice',
            name='country_office',
        ),
        migrations.AddField(
            model_name='countryoffice',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='FieldOffice',
        ),
    ]
