# Generated by Django 2.1 on 2020-11-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0052_auto_20201104_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryoffice',
            options={'ordering': ('name',), 'verbose_name': 'UNICEF Office', 'verbose_name_plural': 'UNICEF Offices'},
        ),
        migrations.AlterModelOptions(
            name='regionaloffice',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='country',
            name='unicef_region',
            field=models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LACR'), (4, 'MENA'), (5, 'SAR'), (6, 'WCAR'), (7, 'HQ')], null=True),
        ),
        migrations.AlterField(
            model_name='countryoffice',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LACR'), (4, 'MENA'), (5, 'SAR'), (6, 'WCAR'), (7, 'HQ')], null=True),
        ),
    ]
