# Generated by Django 2.1 on 2021-12-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0053_auto_20201105_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='unicef_region',
        ),
    ]
