# Generated by Django 2.1 on 2022-03-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0055_auto_20220214_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_included',
            field=models.BooleanField(default=False, help_text='Included in KPI calculations'),
        ),
        migrations.AddField(
            model_name='regionaloffice',
            name='is_empty_option',
            field=models.BooleanField(default=False, help_text='If there is an object to represent N/A, None'),
        ),
        migrations.AddField(
            model_name='regionaloffice',
            name='is_included',
            field=models.BooleanField(default=False, help_text='Included in KPI calculations'),
        ),
    ]
