# Generated by Django 2.1 on 2023-09-05 09:24

import country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0056_auto_20220308_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoffice',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, validators=[country.models.validate_latitude]),
        ),
        migrations.AddField(
            model_name='countryoffice',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[country.models.validate_longitude]),
        ),
    ]
