# Generated by Django 4.2.3 on 2023-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_organisation_id_alter_userprofile_id'),
        ('country', '0056_auto_20220308_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='User who can write questionnaire', related_name='%(class)s_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='map_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='country',
            name='super_admins',
            field=models.ManyToManyField(blank=True, help_text='User who can update landing and all above', related_name='%(class)s_super_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User/viewer who can read confidential answers', related_name='%(class)s_viewers', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='countrycustomquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='countrycustomquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='countryoffice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='User who can write questionnaire', related_name='%(class)s_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='super_admins',
            field=models.ManyToManyField(blank=True, help_text='User who can update landing and all above', related_name='%(class)s_super_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User/viewer who can read confidential answers', related_name='%(class)s_viewers', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donorcustomquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donorcustomquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='donorpartnerlogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regionaloffice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
