# Generated by Django 4.2.3 on 2023-09-10 15:01

import country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0057_alter_country_admins_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoffice',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, validators=[country.models.validate_latitude]),
        ),
        migrations.AddField(
            model_name='countryoffice',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[country.models.validate_longitude]),
        ),
    ]
