# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 12:37
from __future__ import unicode_literals

from django.db import migrations


def fill_data_with_ids(apps, schema_editor):
    Toolkit = apps.get_model('toolkit', 'Toolkit')

    for t in Toolkit.objects.all():
        if t.data:
            domain_counter = 1
            for index, axis in enumerate(t.data):
                t.data[index]['id'] = index + 1
                for domain_index, domain in enumerate(axis['domains']):
                    t.data[index]['domains'][domain_index]['id'] = domain_counter
                    domain_counter += 1
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_auto_20160502_2248'),
    ]

    operations = [
        migrations.RunPython(fill_data_with_ids, migrations.RunPython.noop),
    ]
