# Generated by Django 2.0.7 on 2018-07-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_auto_20180114_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
