# Generated by Django 2.1 on 2022-01-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_django2_20180711_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='toolkitversion',
            name='project',
        ),
        migrations.DeleteModel(
            name='Toolkit',
        ),
        migrations.DeleteModel(
            name='ToolkitVersion',
        ),
    ]
