# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsearch',
            name='health_topic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='organisation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='project_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='technology_platform',
            field=models.TextField(blank=True),
        ),
    ]
