# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160504_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='contact_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='contact_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='geographic_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='implementation_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='implementation_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='implementing_partners',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='intervention_areas',
            field=models.TextField(blank=True),
        ),
    ]
