# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160603_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='mobile_application',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='repository',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='wiki',
            field=models.TextField(blank=True),
        ),
    ]
