# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20160615_0010'),
        ('search', '0005_auto_20160615_0003'),
    ]

    operations = [
    ]
