# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='technology_platform',
        ),
    ]
