# Generated by Django 2.1 on 2018-08-06 13:57

from django.db import migrations


def wipe_all_search_objects(apps, schema_editor):
    PS = apps.get_model("search", "ProjectSearch")
    PS.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_projectsearch_public_id'),
    ]

    operations = [
        migrations.RunPython(wipe_all_search_objects, reverse_code=migrations.RunPython.noop)
    ]
