# Generated by Django 2.1 on 2018-08-06 11:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0034_django2_20180711_1501'),
        ('search', '0010_wipe_all_search_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='geographic_scope',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='health_focus_areas',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='implementation_dates',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='implementation_overview',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='implementing_partners',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='mobile_application',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='wiki',
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country'),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='coverage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='dhi_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='hfa_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='hsc_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='software',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Organisation'),
        ),
        migrations.AlterField(
            model_name='projectsearch',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search', serialize=False, to='project.Project'),
        ),
    ]
