# Generated by Django 2.1 on 2018-08-06 14:02

from django.db import migrations


def regenerate_search_objects(apps, schema_editor):
    PS = apps.get_model("search", "ProjectSearch")
    Project = apps.get_model("project", "Project")
    for project in Project.objects.all():
        PS.objects.get_or_create(project_id=project.id)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180806_1129'),
    ]

    operations = [
        migrations.RunPython(regenerate_search_objects, reverse_code=migrations.RunPython.noop)
    ]
