# Generated by Django 2.1 on 2018-08-13 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_regen_search_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='his',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
