# Generated by Django 2.1 on 2019-01-21 15:04

from django.db import migrations


def update_search_objects(apps, schema_editor):
    pass  # noop


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0015_convert_hsc_categories_to_hsc'),
    ]

    operations = [
        migrations.RunPython(update_search_objects, reverse_code=migrations.RunPython.noop)
    ]
