# Generated by Django 2.1 on 2019-01-21 15:04

from django.db import migrations
from search.models import ProjectSearch

def update_search_objects(apps, schema_editor):
    for search in ProjectSearch.objects.all():
        search.update(search.project)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_convert_hsc_categories_to_hsc'),
    ]

    operations = [
        migrations.RunPython(update_search_objects, reverse_code=migrations.RunPython.noop)
    ]
