# Generated by Django 2.1 on 2019-06-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_update_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='projectsearch',
            name='his',
        ),
    ]
