# Generated by Django 2.1 on 2019-07-30 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20190620_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='capability_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='capability_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='capability_subcategories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
