# Generated by Django 2.1 on 2020-03-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0048_auto_20200312_1243'),
        ('search', '0018_auto_20190730_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='country_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.CountryOffice'),
        ),
    ]
