# Generated by Django 2.1 on 2020-10-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_projectsearch_innovation_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='donor_names',
        ),
    ]
