# Generated by Django 2.1 on 2020-12-08 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_remove_projectsearch_donor_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
