# Generated by Django 2.1 on 2020-12-10 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_projectsearch_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='functions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='hardware',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='infosec',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='innovation_ways',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='nontech',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='regional_priorities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='unicef_sector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
