# Generated by Django 2.1 on 2020-12-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_auto_20201210_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='infosec',
        ),
    ]
