# Generated by Django 2.1 on 2021-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_remove_projectsearch_infosec'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='partner_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
