# Generated by Django 2.1 on 2023-06-12 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_remove_projectsearch_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearch',
            name='unicef_leading_sector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='unicef_supporting_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
