# Generated by Django 4.2.3 on 2023-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltalink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
