# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
    ]
