# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 13:14
from __future__ import unicode_literals

from django.db import migrations


from django.core.management import call_command

fixture = 'initial_sites'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
