# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 18:00
from __future__ import unicode_literals

from django.db import migrations


def create_path_user(apps, schema_editor):
    from django.contrib.auth.models import User
    User.objects.create_superuser('path_user', 'path_user@dhatlas.org', 'p4thu5er')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_sites'),
    ]

    operations = [
        migrations.RunPython(create_path_user)
    ]
