# Generated by Django 2.1 on 2021-10-27 11:58

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_install_pg_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('alt_text', models.CharField(blank=True, max_length=128)),
                ('link', models.URLField()),
                ('link_text', models.CharField(default='Read more >', max_length=64)),
                ('visible', models.BooleanField(default=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='news_images')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
