# Generated by Django 2.1 on 2021-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='alt_text_ar',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='alt_text_fr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='alt_text_pt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_ar',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_es',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description_pt',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_ar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_en',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_es',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_fr',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_pt',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_text_ar',
            field=models.CharField(default='Read more >', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_text_en',
            field=models.CharField(default='Read more >', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_text_es',
            field=models.CharField(default='Read more >', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_text_fr',
            field=models.CharField(default='Read more >', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='link_text_pt',
            field=models.CharField(default='Read more >', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
