# Generated by Django 2.1 on 2022-01-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211027_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-order', '-id']},
        ),
    ]
