# Generated by Django 2.1 on 2022-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220113_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='alt_text_ar',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='link_ar',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='link_text_ar',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='title_ar',
        ),
    ]
