// links: [],
// target_group_reached: 0,

export const nameInventMapping = {
  // INVENT
  unicef_sector: 'Served Sector(s)',
  unicef_leading_sector: 'Leading Sector',
  unicef_supporting_sectors: 'Supporting Sectors',
  functions: 'Function(s) of Platform',
  hardware: 'Hardware platforms',
  nontech: 'Non-Technology platforms',
  regional_priorities: 'Regional Priorities',
  innovation_categories: 'Innovation Categories',
  cpd: 'In Country programme document (CPD)',
  phase: 'Completed phases',
  currency: 'Currency',
  wbs: 'WBS number',
  partners: 'Partners',
  links: 'Links to website/Current Documentation',
  overview: 'Overview',
  program_targets: 'Program Targets',
  program_targets_achieved: 'Program Targets Achieved',
  current_achievements: 'Current Achievements',
  awp: 'Annual Work Plan',
  total_budget_narrative: 'Total Budget (Narrative)',
  funding_needs: 'Funding Needs',
  partnership_needs: 'Partnership Needs',
  total_budget: 'Total Estimated Budget',
  target_group_reached: 'Target Group Reached',
}

export const apiNameInvenMapping = {
  unicef_sector: 'getSectors',
  unicef_leading_sector: 'getLeadingSector',
  unicef_supporting_sectors: 'getSupportingSectors',
  functions: 'getFunctions',
  hardware: 'getHardware',
  nontech: 'getNontech',
  regional_priorities: 'getRegionalPriorities',
  innovation_categories: 'getInnovationCategories',
  cpd: 'getCpd',
  phase: 'getPhases',
  currency: 'getCurrencies',
}

export const nameMapping = {
  name: 'Project Name',
  implementation_overview: 'Initiative Description',
  start_date: 'Project Start Date',
  end_date: 'Project End Date',
  contact_name: 'Programme Focal Point Name',
  contact_email: 'Programme Focal Point Email',
  platforms: 'Software',
  health_focus_areas: 'Health Focus Areas',
  hsc_challenges: 'Health System Challenges',
  dhis: 'Digital Health Interventions',
  goal_area: 'Goal Area',
  result_area: 'Result Area',
  capability_levels: 'Capability Levels',
  capability_categories: 'Capability Categories',
  capability_subcategories: 'Capability Subcategories',
  team: 'Team Members',
  ...nameInventMapping,
}

export const importTemplate = [
  {
    'Project Name': 'MyProject',
    'Initiative Description': 'Narrative free text',
    'Project Start Date': '01/01/2015',
    'Project End Date': '01/01/2019',
    'Programme Focal Point Name': 'Nico',
    'Programme Focal Point Email': 'nico@pulilab.com',
    Software: 'Bamboo|Agora|Adobe Froms',
    'Digital Health Interventions': '3.4.1 Notify birth event|3.4.2 Register birth event',
    'Health Focus Areas': 'Adolescents and communicable diseases|Other sexual and reproductive health',
    'Health System Challenges': '1.1 Lack of population denominator|1.2 Delayed reporting of events',
    'Goal Area': '21. Survive and Thrive',
    'Result Area': '21-01 Maternal and newborn health',
    Overview: 'text',
    'Program Targets': 'text',
    'Program Targets Achieved': 'text',
    'Current Achievements': 'text',
    'Annual Work Plan': 'text',
    'Total Budget (Narrative)': 'text',
    'Funding Needs': 'text',
    'Partnership Needs': 'text',
    'WBS number': '1|2',
    Currency: 'US Dollar',
    'Total Estimated Budget': '0',
    'Target Group Reached': '0',
    'Links to website/Current Documentation':
      'Website|https://invent.unicef.org|SharePoint|https://invent.unicef.org|External|https://invent.unicef.org|Monitoring|https://invent.unicef.org|Other|https://invent.unicef.org',
    Partners:
      'Investor Partner|Investor Name|Investor Contact|partner@investor.com|https://www.investor.com|Technology Partner|Partner Name|Partner Contact|partner@technology.com|https://www.technology.com',
    'Team Members': 'db@unicef.org|db+test@unicef.org',
  },
  {
    'Project Name': 'MyProject2',
    'Initiative Description': 'Narrative free text',
    'Project Start Date': '04/22/2015',
    'Project End Date': '03/22/2019',
    'Programme Focal Point Name': 'Nico',
    'Programme Focal Point Email': 'nico@pulilab.com',
    Software: 'Bamboo',
    'Goal Area': '22. Learn',
    'Result Area': '22-01 Equitable access to quality education',
    'Capability Levels': '4. Interventions for data services',
    'Capability Categories': '1.3 Student to student communication',
    'Capability Subcategories': '1.1.1 Transmit education event alerts to specific population group(s)',
    Overview: '',
    'Program Targets': '',
    'Program Targets Achieved': '',
    'Current Achievements': '',
    'Annual Work Plan': '',
    'Total Budget (Narrative)': '',
    'Funding Needs': '',
    'Partnership Needs': '',
  },
]
