export const nameMapping = {
  name: 'Project Name',
  organisation: 'Organisation',
  geographic_scope: 'Geographic Scope',
  implementation_overview: 'Narrative of the project',
  start_date: 'Start Date',
  end_date: 'End Date',
  contact_name: 'Contact name',
  contact_email: 'Contact email',
  platforms: 'Software',
  health_focus_areas: 'Health Focus Areas',
  hsc_challenges: 'Health System Challenges',
  his_bucket: 'Health Information Systems',
  government_investor: 'Governament Contribution',
  implementing_partners: 'Partners',
  implementation_dates: 'Technology Deployment Date',
  licenses: 'Licenses',
  repository: 'Link to Code documentation',
  wiki: 'Link to Wiki',
  mobile_application: 'Link to application',
  interoperability_links: 'Interoperability Links',
  interoperability_standards: 'Interoperability Standards',
  health_workers: 'Health Workers',
  clients: 'Clients',
  facilities: 'Facilities',
  sub_level: 'Coverage Type',
  digitalHealthInterventions: 'Digital Health Interventions (associated to the Software)'
};

export const importTemplate = [
  {
    'Project Name': 'MyProject',
    'Organisation': 'WHO',
    'Geographic Scope': 'Gographipc Scope Free Text',
    'Narrative of the project': 'Narrative free text',
    'Start Date': 43742,
    'End Date': 43875,
    'Contact name': 'Nico',
    'Contact email': 'nico@pulilab.com',
    'Software': 'Bamboo',
    'Digital Health Interventions (associated to the Software)': '3.4.1 Notify birth event, 3.4.2 Register birth event',
    'Health Focus Areas': 'Adolescents and communicable diseases, Other sexual and reproductive health',
    'Health System Challenges': '1.1 Lack of population denominator,\n1.2 Delayed reporting of events',
    'Health Information Systems': 'A. Census, population information & data warehouse, B. Civil Registration and Vital Statistics',
    'Governament Contribution': 'no they have not yet contributed',
    'Partners': 'Partner_one, Partner two',
    'Technology Deployment Date': 43742,
    'Licenses': 'Proprietary, Fremium',
    'Link to Code documentation': 'http://www.valid.link.org',
    'Link to Wiki': 'http://www.valid.link.org',
    'Link to application': 'http://www.valid.link.org',
    'Interoperability Standards': 'ADX - Aggregate Data Exchange,\nCDA - Clinical Document Architecture',
    'Coverage Type': 'National Level',
    'Health Workers': 1,
    'Clients': 2,
    'Facilities': 3
  },
  {
    'Project Name': 'MyProject2',
    'Organisation': 'WHO',
    'Geographic Scope': 'Gographipc Scope Free Text',
    'Narrative of the project': 'Narrative free text',
    'Start Date': 43742,
    'End Date': 43875,
    'Contact name': 'Nico',
    'Contact email': 'nico@pulilab.com',
    'Software': 'Bamboo',
    'Digital Health Interventions (associated to the Software)': '3.4.1 Notify birth event, 3.4.2 Register birth event',
    'Health Focus Areas': 'Adolescents and communicable diseases, Other sexual and reproductive health',
    'Health System Challenges': '1.1 Lack of population denominator,\n1.2 Delayed reporting of events',
    'Health Information Systems': 'A. Census, population information & data warehouse, B. Civil Registration and Vital Statistics',
    'Governament Contribution': 'no they have not yet contributed',
    'Partners': 'Partner_one, Partner two',
    'Technology Deployment Date': 43742,
    'Licenses': 'Proprietary, Fremium',
    'Link to Code documentation': 'http://www.valid.link.org',
    'Link to Wiki': 'http://www.valid.link.org',
    'Link to application': 'http://www.valid.link.org',
    'Interoperability Standards': 'ADX - Aggregate Data Exchange,\nCDA - Clinical Document Architecture',
    'Coverage Type': '"Selected Country Sub Level name"',
    'Health Workers': 1,
    'Clients': 2,
    'Facilities': 3
  }
];
