# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_auto_20160719_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(1, 'Resources'), (2, 'Lessons & Tips'), (3, 'Experiences')], default=1)),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(1, 'Resources'), (2, 'Lessons & Tips'), (3, 'Experiences')], default=1)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(max_length=5000)),
                ('type', models.IntegerField(choices=[(1, 'Resources'), (2, 'Lessons & Tips'), (3, 'Experiences')])),
                ('domain', models.IntegerField(choices=[(1, 'Parameters of Scale'), (2, 'Contextual Environment'), (3, 'Scientific Basis'), (4, 'Strategic Engagement'), (5, 'Partnership Sustainability'), (6, 'Financial Management'), (7, 'Financial Model'), (8, 'Data'), (9, 'Interoperability'), (10, 'Adaptability'), (11, 'Personnel'), (12, 'Training and Support'), (13, 'Outreach and Sensitization'), (14, 'Contingency Planning'), (15, 'Process Monitoring'), (16, 'Evaluation Research')])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
