# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170509_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Planning & Guidance post', 'verbose_name_plural': 'Planning & Guidance posts'},
        ),
    ]
