# Generated by Django 2.1 on 2022-01-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_django2_20180711_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
