mappings = [
    ("Afghanistan: Badghis", "N/A", "Badghis", "Afghanistan", "SAR"),
    ("Afghanistan: Bamyan", "N/A", "Bamyan", "Afghanistan", "SAR"),
    ("Afghanistan: Daikundi", "N/A", "Daikundi", "Afghanistan", "SAR"),
    ("Afghanistan: Faizabad", "N/A", "Faizabad", "Afghanistan", "SAR"),
    ("Afghanistan: Gardez", "N/A", "Gardez", "Afghanistan", "SAR"),
    ("Afghanistan: Ghor", "N/A", "Ghor", "Afghanistan", "SAR"),
    ("Afghanistan: Herat", "N/A", "Herat", "Afghanistan", "SAR"),
    ("Afghanistan: Jalalabad", "N/A", "Jalalabad", "Afghanistan", "SAR"),
    ("Afghanistan: Kabul", "N/A", "Kabul", "Afghanistan", "SAR"),
    ("Afghanistan: Kandahar", "N/A", "Kandahar", "Afghanistan", "SAR"),
    ("Afghanistan: Mazar-i-Sharif", "N/A", "Mazar-i-Sharif", "Afghanistan", "SAR"),
    ("Albania: Tirana", "N/A", "Tirana", "Albania", "ECAR"),
    ("Algeria: Algiers", "N/A", "Algiers", "Algeria", "MENA"),
    ("Algeria: Tindouf", "N/A", "Tindouf", "Algeria", "MENA"),
    ("Angola: Dundo", "N/A", "Dundo", "Angola", "ESAR"),
    ("Angola: Kuito Bie", "N/A", "Kuito Bie", "Angola", "ESAR"),
    ("Angola: Kunene", "N/A", "Kunene", "Angola", "ESAR"),
    ("Angola: Luanda", "N/A", "Luanda", "Angola", "ESAR"),
    ("Angola: Lubango", "N/A", "Lubango", "Angola", "ESAR"),
    ("Argentina: Buenos Aires", "N/A", "Buenos Aires", "Argentina", "LACR"),
    ("Armenia: Yerevan", "N/A", "Yerevan", "Armenia", "ECAR"),
    (
        "Australian National Committee: Australia: Sydney", "Australian National Committee", "Sydney", "Australia",
        "EAPR"),
    ("Azerbaijan: Baku", "N/A", "Baku", "Azerbaijan", "ECAR"),
    ("Bangladesh: Barisal", "N/A", "Barisal", "Bangladesh", "SAR"),
    ("Bangladesh: Bogra", "N/A", "Bogra", "Bangladesh", "SAR"),
    ("Bangladesh: Chattogram", "N/A", "Chattogram", "Bangladesh", "SAR"),
    ("Bangladesh: Cox's Bazaar", "N/A", "Cox's Bazaar", "Bangladesh", "SAR"),
    ("Bangladesh: Dhaka", "N/A", "Dhaka", "Bangladesh", "SAR"),
    ("Bangladesh: Khulna", "N/A", "Khulna", "Bangladesh", "SAR"),
    ("Bangladesh: Mymensingh", "N/A", "Mymensingh", "Bangladesh", "SAR"),
    ("Bangladesh: Rangamati", "N/A", "Rangamati", "Bangladesh", "SAR"),
    ("Bangladesh: Rangpur", "N/A", "Rangpur", "Bangladesh", "SAR"),
    ("Bangladesh: Sylhet", "N/A", "Sylhet", "Bangladesh", "SAR"),
    ("Belarus: Minsk", "N/A", "Minsk", "Belarus", "ECAR"),
    ("Belize: Belize City", "N/A", "Belize City", "Belize", "LACR"),
    ("Benin: Cotonou", "N/A", "Cotonou", "Benin", "WCAR"),
    ("Benin: Parakou", "N/A", "Parakou", "Benin", "WCAR"),
    ("Bhutan: Thimphu", "N/A", "Thimphu", "Bhutan", "SAR"),
    ("Bolivia (Plurinational State of): Cochabamba", "N/A", "Cochabamba", "Bolivia (Plurinational State of)", "LACR"),
    ("Bolivia (Plurinational State of): La Paz", "N/A", "La Paz", "Bolivia (Plurinational State of)", "LACR"),
    ("Bosnia And Herzegovina: Bihac", "N/A", "Bihac", "Bosnia And Herzegovina", "ECAR"),
    ("Bosnia And Herzegovina: Sarajevo", "N/A", "Sarajevo", "Bosnia And Herzegovina", "ECAR"),
    ("Botswana: Gaborone", "N/A", "Gaborone", "Botswana", "ESAR"),
    ("Brazil: Belem", "N/A", "Belem", "Brazil", "LACR"),
    ("Brazil: Boa Vista", "N/A", "Boa Vista", "Brazil", "LACR"),
    ("Brazil: Brasilia", "N/A", "Brasilia", "Brazil", "LACR"),
    ("Brazil: Fortaleza", "N/A", "Fortaleza", "Brazil", "LACR"),
    ("Brazil: Manaus", "N/A", "Manaus", "Brazil", "LACR"),
    ("Brazil: Recife", "N/A", "Recife", "Brazil", "LACR"),
    ("Brazil: Rio de Janeiro", "N/A", "Rio de Janeiro", "Brazil", "LACR"),
    ("Brazil: Salvador", "N/A", "Salvador", "Brazil", "LACR"),
    ("Brazil: Sao Luis", "N/A", "Sao Luis", "Brazil", "LACR"),
    ("Brazil: Sao Paulo", "N/A", "Sao Paulo", "Brazil", "LACR"),
    ("Bulgaria: Sofia", "N/A", "Sofia", "Bulgaria", "ECAR"),
    ("Burkina Faso: Dori", "N/A", "Dori", "Burkina Faso", "WCAR"),
    ("Burkina Faso: Kaya", "N/A", "Kaya", "Burkina Faso", "WCAR"),
    ("Burkina Faso: Ouagadougou", "N/A", "Ouagadougou", "Burkina Faso", "WCAR"),
    ("Burundi: Bujumbura", "N/A", "Bujumbura", "Burundi", "ESAR"),
    ("Cambodia: Kratie", "N/A", "Kratie", "Cambodia", "EAPR"),
    ("Cambodia: Phnom Penh", "N/A", "Phnom Penh", "Cambodia", "EAPR"),
    ("Cambodia: Siem Reap", "N/A", "Siem Reap", "Cambodia", "EAPR"),
    ("Cameroon: Bertoua", "N/A", "Bertoua", "Cameroon", "WCAR"),
    ("Cameroon: Douala", "N/A", "Douala", "Cameroon", "WCAR"),
    ("Cameroon: Maroua", "N/A", "Maroua", "Cameroon", "WCAR"),
    ("Cameroon: Yaounde", "N/A", "Yaounde", "Cameroon", "WCAR"),
    ("Central African Republic: Bambari", "N/A", "Bambari", "Central African Republic", "WCAR"),
    ("Central African Republic: Bangui", "N/A", "Bangui", "Central African Republic", "WCAR"),
    ("Central African Republic: Bossangoa", "N/A", "Bossangoa", "Central African Republic", "WCAR"),
    ("Central African Republic: Bouar", "N/A", "Bouar", "Central African Republic", "WCAR"),
    ("Central African Republic: Kaga Bandoro", "N/A", "Kaga Bandoro", "Central African Republic", "WCAR"),
    ("Chad: Abeche", "N/A", "Abeche", "Chad", "WCAR"),
    ("Chad: Bol", "N/A", "Bol", "Chad", "WCAR"),
    ("Chad: Mao", "N/A", "Mao", "Chad", "WCAR"),
    ("Chad: Mongo", "N/A", "Mongo", "Chad", "WCAR"),
    ("Chad: Moundou", "N/A", "Moundou", "Chad", "WCAR"),
    ("Chad: N'Djamena", "N/A", "N'Djamena", "Chad", "WCAR"),
    ("Chile: Santiago", "N/A", "Santiago", "Chile", "LACR"),
    ("China: Beijing", "N/A", "Beijing", "China", "EAPR"),
    ("Colombia: Bogota", "N/A", "Bogota", "Colombia", "LACR"),
    ("Comoros: Moroni", "N/A", "Moroni", "Comoros", "ESAR"),
    ("Congo: Brazzaville", "N/A", "Brazzaville", "Congo", "WCAR"),
    ("Congo: Pointe-Noire", "N/A", "Pointe-Noire", "Congo", "WCAR"),
    ("Costa Rica: San Jose", "N/A", "San Jose", "Costa Rica", "LACR"),
    ("Côte d’Ivoire: Abidjan", "N/A", "Abidjan", "Côte d’Ivoire", "WCAR"),
    ("Côte d’Ivoire: Korhogo", "N/A", "Korhogo", "Côte d’Ivoire", "WCAR"),
    ("Côte d’Ivoire: Man", "N/A", "Man", "Côte d’Ivoire", "WCAR"),
    ("Croatia: Zagreb", "N/A", "Zagreb", "Croatia", "ECAR"),
    ("Cuba: Havana", "N/A", "Havana", "Cuba", "LACR"),
    ("Democratic People's Republic of Korea: Pyongyang", "N/A", "Pyongyang", "Democratic People's Republic of Korea",
     "EAPR"),
    ("Democratic Republic of the Congo: Bukavu", "N/A", "Bukavu", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Bunia", "N/A", "Bunia", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Goma", "N/A", "Goma", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Kalemie", "N/A", "Kalemie", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Kananga", "N/A", "Kananga", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Kinshasa", "N/A", "Kinshasa", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Kisangani", "N/A", "Kisangani", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Lubumbashi", "N/A", "Lubumbashi", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Mbandaka", "N/A", "Mbandaka", "Democratic Republic of the Congo", "WCAR"),
    ("Democratic Republic of the Congo: Mbuji Mayi", "N/A", "Mbuji Mayi", "Democratic Republic of the Congo", "WCAR"),
    ("Djibouti: Djibouti", "N/A", "Djibouti", "Djibouti", "MENA"),
    ("Dominican Republic: Santo Domingo", "N/A", "Santo Domingo", "Dominican Republic", "LACR"),
    ("EAPRO: Bangkok", "EAPRO", "Bangkok", "Thailand", "EAPR"),
    ("Eastern Carribean: Anguilla: The Valley", "Eastern Carribean", "The Valley", "Anguilla", "LACR"),
    ("Eastern Carribean: Antigua and Barbuda: Saint John's", "Eastern Carribean", "Saint John's", "Antigua and Barbuda",
     "LACR"),
    ("Eastern Carribean: Barbados: Castries", "Eastern Carribean", "Castries", "Barbados", "LACR"),
    ("Eastern Carribean: Barbados: Port of Spain", "Eastern Carribean", "Port of Spain", "Barbados", "LACR"),
    ("Eastern Carribean: British Virgin Islands: Road Town", "Eastern Carribean", "Road Town", "British Virgin Islands",
     "LACR"),
    ("Eastern Carribean: Dominica: Roseau", "Eastern Carribean", "Roseau", "Dominica", "LACR"),
    ("Eastern Carribean: Grenada: Saint George's", "Eastern Carribean", "Saint George's", "Grenada", "LACR"),
    ("Eastern Carribean: Montserrat: Brades", "Eastern Carribean", "Brades", "Montserrat", "LACR"),
    ("Eastern Carribean: Saint Kitts and Nevis: Basseterre", "Eastern Carribean", "Basseterre", "Saint Kitts and Nevis",
     "LACR"),
    ("Eastern Carribean: Saint Lucia: Castries", "Eastern Carribean", "Castries", "Saint Lucia", "LACR"),
    ("Eastern Carribean: Saint Vincent and the Grenadines: Kingstown", "Eastern Carribean", "Kingstown",
     "Saint Vincent and the Grenadines", "LACR"),
    ("Eastern Carribean: Trinidad and Tobago: Port of Spain", "Eastern Carribean", "Port of Spain",
     "Trinidad and Tobago", "LACR"),
    ("Eastern Carribean: Turks and Caicos Islands: Cockburn Town", "Eastern Carribean", "Cockburn Town",
     "Turks and Caicos Islands", "LACR"),
    ("ECARO: Geneva", "ECARO", "Geneva", "Switzerland", "ECAR"),
    ("Ecuador: Esmeraldas", "N/A", "Esmeraldas", "Ecuador", "LACR"),
    ("Ecuador: Pedernales", "N/A", "Pedernales", "Ecuador", "LACR"),
    ("Ecuador: Quito", "N/A", "Quito", "Ecuador", "LACR"),
    ("Egypt: Cairo", "N/A", "Cairo", "Egypt", "MENA"),
    ("El Salvador: San Salvador", "N/A", "San Salvador", "El Salvador", "LACR"),
    ("Equatorial Guinea: Bata", "N/A", "Bata", "Equatorial Guinea", "WCAR"),
    ("Equatorial Guinea: Malabo", "N/A", "Malabo", "Equatorial Guinea", "WCAR"),
    ("Eritrea: Asmara", "N/A", "Asmara", "Eritrea", "ESAR"),
    ("ESARO: Johannesburg", "ESARO", "Johannesburg", "South Africa", "ESAR"),
    ("ESARO: Nairobi", "ESARO", "Nairobi", "Kenya", "ESAR"),
    ("Eswatini: Mbabane", "N/A", "Mbabane", "Eswatini", "ESAR"),
    ("Ethiopia: Addis Ababa", "N/A", "Addis Ababa", "Ethiopia", "ESAR"),
    ("Ethiopia: Assosa", "N/A", "Assosa", "Ethiopia", "ESAR"),
    ("Ethiopia: Awasa", "N/A", "Awasa", "Ethiopia", "ESAR"),
    ("Ethiopia: Bahir Dar", "N/A", "Bahir Dar", "Ethiopia", "ESAR"),
    ("Ethiopia: Gambela", "N/A", "Gambela", "Ethiopia", "ESAR"),
    ("Ethiopia: Jijiga", "N/A", "Jijiga", "Ethiopia", "ESAR"),
    ("Ethiopia: Mekelle", "N/A", "Mekelle", "Ethiopia", "ESAR"),
    ("Ethiopia: Semera", "N/A", "Semera", "Ethiopia", "ESAR"),
    ("Gabon: Libreville", "N/A", "Libreville", "Gabon", "WCAR"),
    ("Gambia: Banjul", "N/A", "Banjul", "Gambia", "WCAR"),
    ("Georgia: Sukhumi", "N/A", "Sukhumi", "Georgia", "ECAR"),
    ("Georgia: Tbilisi", "N/A", "Tbilisi", "Georgia", "ECAR"),
    ("Ghana: Accra", "N/A", "Accra", "Ghana", "WCAR"),
    ("Ghana: Tamale", "N/A", "Tamale", "Ghana", "WCAR"),
    ("Guatemala: Guatemala City", "N/A", "Guatemala City", "Guatemala", "LACR"),
    ("Guinea-Bissau: Bissau", "N/A", "Bissau", "Guinea-Bissau", "WCAR"),
    ("Guinea: Conakry", "N/A", "Conakry", "Guinea", "WCAR"),
    ("Guinea: Kankan", "N/A", "Kankan", "Guinea", "WCAR"),
    ("Guinea: Labe", "N/A", "Labe", "Guinea", "WCAR"),
    ("Guinea: Nzerekore", "N/A", "Nzerekore", "Guinea", "WCAR"),
    ("Gulf Area Office: Bahrain: Manama", "Gulf Area Office", "Manama", "Bahrain", "MENA"),
    ("Gulf Area Office: Kuwait: Kuwait City", "Gulf Area Office", "Kuwait City", "Kuwait", "MENA"),
    ("Gulf Area Office: Qatar: Doha", "Gulf Area Office", "Doha", "Qatar", "MENA"),
    ("Gulf Area Office: Saudi Arabia: Riyadh", "Gulf Area Office", "Riyadh", "Saudi Arabia", "MENA"),
    ("Gulf Area Office: United Arab Emirates: Abu Dhabi", "Gulf Area Office", "Abu Dhabi", "United Arab Emirates",
     "MENA"),
    ("Gulf Area Office: United Arab Emirates: Dubai", "Gulf Area Office", "Dubai", "United Arab Emirates", "MENA"),
    ("Guyana: Georgetown", "N/A", "Georgetown", "Guyana", "LACR"),
    ("Haiti: Cap Haitien", "N/A", "Cap Haitien", "Haiti", "LACR"),
    ("Haiti: Gonaives", "N/A", "Gonaives", "Haiti", "LACR"),
    ("Haiti: Jeremie/Dame-Marie", "N/A", "Jeremie/Dame-Marie", "Haiti", "LACR"),
    ("Haiti: Les Cayes", "N/A", "Les Cayes", "Haiti", "LACR"),
    ("Haiti: Port-au-Prince", "N/A", "Port-au-Prince", "Haiti", "LACR"),
    ("Honduras: Tegucigalpa", "N/A", "Tegucigalpa", "Honduras", "LACR"),
    ("Hong Kong Committee: China, Hong Kong Special Administrative Region: Hong Kong", "Hong Kong Committee",
     "Hong Kong", "China, Hong Kong Special Administrative Region", "EAPR"),
    ("HQ: Brussels: Belgium", "HQ", "Brussels", "Belgium", "HQ"),
    ("HQ: Budapest: Hungary", "HQ", "Budapest", "Hungary", "HQ"),
    ("HQ: Copenhagen: Denmark", "HQ", "Copenhagen", "Denmark", "HQ"),
    ("HQ: Florence: Italy", "HQ", "Florence", "Italy", "HQ"),
    ("HQ: Geneva: Switzerland", "HQ", "Geneva", "Switzerland", "HQ"),
    ("HQ: New York: United States Of America", "HQ", "New York", "United States Of America", "HQ"),
    ("HQ: Rome: Italy", "HQ", "Rome", "Italy", "HQ"),
    ("HQ: Seoul: Republic of Korea", "HQ", "Seoul", "Republic of Korea", "HQ"),
    ("HQ: Tokyo: Japan", "HQ", "Tokyo", "Japan", "HQ"),
    ("HQ: Turin: Italy", "HQ", "Turin", "Italy", "HQ"),
    ("HQ: Valencia", "HQ", "Valencia", "Spain", "HQ"),
    ("HQ: Washington", "HQ", "Washington", "United States Of America", "HQ"),
    ("India: Bhopal", "N/A", "Bhopal", "India", "SAR"),
    ("India: Bhubaneswar", "N/A", "Bhubaneswar", "India", "SAR"),
    ("India: Chennai", "N/A", "Chennai", "India", "SAR"),
    ("India: Gandhinagar", "N/A", "Gandhinagar", "India", "SAR"),
    ("India: Guwahati", "N/A", "Guwahati", "India", "SAR"),
    ("India: Hyderabad", "N/A", "Hyderabad", "India", "SAR"),
    ("India: Jaipur", "N/A", "Jaipur", "India", "SAR"),
    ("India: Kolkata", "N/A", "Kolkata", "India", "SAR"),
    ("India: Lucknow", "N/A", "Lucknow", "India", "SAR"),
    ("India: Mumbai", "N/A", "Mumbai", "India", "SAR"),
    ("India: New Delhi", "N/A", "New Delhi", "India", "SAR"),
    ("India: Patna", "N/A", "Patna", "India", "SAR"),
    ("India: Raipur", "N/A", "Raipur", "India", "SAR"),
    ("India: Ranchi", "N/A", "Ranchi", "India", "SAR"),
    ("India: Srinagar", "N/A", "Srinagar", "India", "SAR"),
    ("Indonesia: Ambon", "N/A", "Ambon", "Indonesia", "EAPR"),
    ("Indonesia: Banda Aceh", "N/A", "Banda Aceh", "Indonesia", "EAPR"),
    ("Indonesia: Jakarta", "N/A", "Jakarta", "Indonesia", "EAPR"),
    ("Indonesia: Jayapura", "N/A", "Jayapura", "Indonesia", "EAPR"),
    ("Indonesia: Kupang", "N/A", "Kupang", "Indonesia", "EAPR"),
    ("Indonesia: Makassar", "N/A", "Makassar", "Indonesia", "EAPR"),
    ("Indonesia: Manokwari", "N/A", "Manokwari", "Indonesia", "EAPR"),
    ("Indonesia: Surabaya", "N/A", "Surabaya", "Indonesia", "EAPR"),
    ("Iran (Islamic Republic of): Tehran", "N/A", "Tehran", "Iran (Islamic Republic of)", "MENA"),
    ("Iraq: Al Basrah", "N/A", "Al Basrah", "Iraq", "MENA"),
    ("Iraq: Baghdad", "N/A", "Baghdad", "Iraq", "MENA"),
    ("Iraq: Dohuk", "N/A", "Dohuk", "Iraq", "MENA"),
    ("Iraq: Erbil", "N/A", "Erbil", "Iraq", "MENA"),
    ("Jamaica: Kingston", "N/A", "Kingston", "Jamaica", "LACR"),
    ("Japan National Committee: Japan: Tokyo", "Japan National Committee", "Tokyo", "Japan", "EAPR"),
    ("Jordan: Amman", "N/A", "Amman", "Jordan", "MENA"),
    ("Jordan: Ruwayshid", "N/A", "Ruwayshid", "Jordan", "MENA"),
    ("Kazakhstan: Almaty", "N/A", "Almaty", "Kazakhstan", "ECAR"),
    ("Kazakhstan: Astana", "N/A", "Astana", "Kazakhstan", "ECAR"),
    ("Kenya: Dadaab", "N/A", "Dadaab", "Kenya", "ESAR"),
    ("Kenya: Garissa", "N/A", "Garissa", "Kenya", "ESAR"),
    ("Kenya: Kisumu", "N/A", "Kisumu", "Kenya", "ESAR"),
    ("Kenya: Lodwar", "N/A", "Lodwar", "Kenya", "ESAR"),
    ("Kenya: Nairobi", "N/A", "Nairobi", "Kenya", "ESAR"),
    ("Korea National Committee: Republic of Korea: Seoul", "Korea National Committee", "Seoul", "Republic of Korea",
     "EAPR"),
    ("Kosovo (UNSCR 1244/99): Prishtina", "N/A", "Prishtina", "Kosovo (UNSCR 1244/99)", "ECAR"),
    ("Kosovo (UNSCR 1244/99): Zvecan", "N/A", "Zvecan", "Kosovo (UNSCR 1244/99)", "ECAR"),
    ("Kyrgyzstan: Bishkek", "N/A", "Bishkek", "Kyrgyzstan", "ECAR"),
    ("Kyrgyzstan: Osh", "N/A", "Osh", "Kyrgyzstan", "ECAR"),
    ("LACRO: Panama City", "LACRO", "Panama City", "Panama", "LACR"),
    ("Lao People's Democratic Republic: Vientiane", "N/A", "Vientiane", "Lao People's Democratic Republic", "EAPR"),
    ("Lebanon: Beirut", "N/A", "Beirut", "Lebanon", "MENA"),
    ("Lebanon: Qobayat", "N/A", "Qobayat", "Lebanon", "MENA"),
    ("Lebanon: Tripoli", "N/A", "Tripoli", "Lebanon", "MENA"),
    ("Lebanon: Tyre", "N/A", "Tyre", "Lebanon", "MENA"),
    ("Lebanon: Zahle", "N/A", "Zahle", "Lebanon", "MENA"),
    ("Lesotho: Maseru", "N/A", "Maseru", "Lesotho", "ESAR"),
    ("Liberia: Monrovia", "N/A", "Monrovia", "Liberia", "WCAR"),
    ("Libya: Tripoli", "N/A", "Tripoli", "Libya", "MENA"),
    ("Madagascar: Ambovombe", "N/A", "Ambovombe", "Madagascar", "ESAR"),
    ("Madagascar: Antananarivo", "N/A", "Antananarivo", "Madagascar", "ESAR"),
    ("Madagascar: Fort-Dauphin", "N/A", "Fort-Dauphin", "Madagascar", "ESAR"),
    ("Madagascar: Mahajanga", "N/A", "Mahajanga", "Madagascar", "ESAR"),
    ("Madagascar: Manakara", "N/A", "Manakara", "Madagascar", "ESAR"),
    ("Madagascar: Toamasina", "N/A", "Toamasina", "Madagascar", "ESAR"),
    ("Madagascar: Toliara (Tulear)", "N/A", "Toliara (Tulear)", "Madagascar", "ESAR"),
    ("Malawi: Lilongwe", "N/A", "Lilongwe", "Malawi", "ESAR"),
    ("Malaysia: Kuala Lumpur", "N/A", "Kuala Lumpur", "Malaysia", "EAPR"),
    ("Maldives: Male", "N/A", "Male", "Maldives", "SAR"),
    ("Mali: Bamako", "N/A", "Bamako", "Mali", "WCAR"),
    ("Mali: Gao", "N/A", "Gao", "Mali", "WCAR"),
    ("Mali: Kayes", "N/A", "Kayes", "Mali", "WCAR"),
    ("Mali: Mopti", "N/A", "Mopti", "Mali", "WCAR"),
    ("Mali: Segou", "N/A", "Segou", "Mali", "WCAR"),
    ("Mali: Sikasso", "N/A", "Sikasso", "Mali", "WCAR"),
    ("Mali: Timbuktu", "N/A", "Timbuktu", "Mali", "WCAR"),
    ("Mauritania: Bassikounou", "N/A", "Bassikounou", "Mauritania", "WCAR"),
    ("Mauritania: Kiffa", "N/A", "Kiffa", "Mauritania", "WCAR"),
    ("Mauritania: Nouakchott", "N/A", "Nouakchott", "Mauritania", "WCAR"),
    ("MENARO: Amman", "MENARO", "Amman", "Jordan", "MENA"),
    ("Mexico: Mexico City", "N/A", "Mexico City", "Mexico", "LACR"),
    ("Mongolia: Ulaanbaatar", "N/A", "Ulaanbaatar", "Mongolia", "EAPR"),
    ("Montenegro: Podgorica", "N/A", "Podgorica", "Montenegro", "ECAR"),
    ("Morocco: Rabat", "N/A", "Rabat", "Morocco", "MENA"),
    ("Mozambique: Beira", "N/A", "Beira", "Mozambique", "ESAR"),
    ("Mozambique: Maputo", "N/A", "Maputo", "Mozambique", "ESAR"),
    ("Myanmar: Hakha", "N/A", "Hakha", "Myanmar", "EAPR"),
    ("Myanmar: Lashio", "N/A", "Lashio", "Myanmar", "EAPR"),
    ("Myanmar: Mandalay", "N/A", "Mandalay", "Myanmar", "EAPR"),
    ("Myanmar: Maungdaw", "N/A", "Maungdaw", "Myanmar", "EAPR"),
    ("Myanmar: Myitkyina", "N/A", "Myitkyina", "Myanmar", "EAPR"),
    ("Myanmar: Nay Pyi Taw", "N/A", "Nay Pyi Taw", "Myanmar", "EAPR"),
    ("Myanmar: Taunggyi", "N/A", "Taunggyi", "Myanmar", "EAPR"),
    ("Myanmar: Yangon", "N/A", "Yangon", "Myanmar", "EAPR"),
    ("Namibia: Windhoek", "N/A", "Windhoek", "Namibia", "ESAR"),
    ("Nepal: Bharatpur", "N/A", "Bharatpur", "Nepal", "SAR"),
    ("Nepal: Biratnagar", "N/A", "Biratnagar", "Nepal", "SAR"),
    ("Nepal: Dadeldhura", "N/A", "Dadeldhura", "Nepal", "SAR"),
    ("Nepal: Janakpur", "N/A", "Janakpur", "Nepal", "SAR"),
    ("Nepal: Kathmandu", "N/A", "Kathmandu", "Nepal", "SAR"),
    ("Nepal: Nepalgunj", "N/A", "Nepalgunj", "Nepal", "SAR"),
    ("Nepal: Pokhara", "N/A", "Pokhara", "Nepal", "SAR"),
    ("New Zealand National Committee: New Zealand: Wellington", "New Zealand National Committee", "Wellington",
     "New Zealand", "EAPR"),
    ("Nicaragua: Managua", "N/A", "Managua", "Nicaragua", "LACR"),
    ("Niger: Agadez", "N/A", "Agadez", "Niger", "WCAR"),
    ("Niger: Diffa", "N/A", "Diffa", "Niger", "WCAR"),
    ("Niger: Maradi", "N/A", "Maradi", "Niger", "WCAR"),
    ("Niger: Niamey", "N/A", "Niamey", "Niger", "WCAR"),
    ("Nigeria: Abuja", "N/A", "Abuja", "Nigeria", "WCAR"),
    ("Nigeria: Akure", "N/A", "Akure", "Nigeria", "WCAR"),
    ("Nigeria: Bauchi", "N/A", "Bauchi", "Nigeria", "WCAR"),
    ("Nigeria: Enugu", "N/A", "Enugu", "Nigeria", "WCAR"),
    ("Nigeria: Kaduna", "N/A", "Kaduna", "Nigeria", "WCAR"),
    ("Nigeria: Kano", "N/A", "Kano", "Nigeria", "WCAR"),
    ("Nigeria: Katsina", "N/A", "Katsina", "Nigeria", "WCAR"),
    ("Nigeria: Lagos", "N/A", "Lagos", "Nigeria", "WCAR"),
    ("Nigeria: Maiduguri", "N/A", "Maiduguri", "Nigeria", "WCAR"),
    ("Nigeria: Port Harcourt", "N/A", "Port Harcourt", "Nigeria", "WCAR"),
    ("Nigeria: Sokoto", "N/A", "Sokoto", "Nigeria", "WCAR"),
    ("North Macedonia: Skopje", "N/A", "Skopje", "North Macedonia", "ECAR"),
    ("Office for the Eastern Caribbean Area: Barbados: Bridgetown", "Office for the Eastern Caribbean Area",
     "Bridgetown", "Barbados", "LACR"),
    ("Oman: Muscat", "N/A", "Muscat", "Oman", "MENA"),
    ("Pacific Multi Country Office: Fiji: Suva", "Pacific Multi Country Office", "Suva", "Fiji", "EAPR"),
    ("Pacific: Cook Islands: Avarua District", "Pacific", "Avarua District", "Cook Islands", "EAPR"),
    ("Pacific: Fiji: Suva", "Pacific", "Suva", "Fiji", "EAPR"),
    ("Pacific: Kiribati: Tarawa", "Pacific", "Tarawa", "Kiribati", "EAPR"),
    ("Pacific: Marshall Islands: Majuro", "Pacific", "Majuro", "Marshall Islands", "EAPR"),
    ("Pacific: Micronesia (Federated States of): Palikir", "Pacific", "Palikir", "Micronesia (Federated States of)",
     "EAPR"),
    ("Pacific: Nauru: Yaren District", "Pacific", "Yaren District", "Nauru", "EAPR"),
    ("Pacific: Niue: Alofi", "Pacific", "Alofi", "Niue", "EAPR"),
    ("Pacific: Palau: Ngerulmud", "Pacific", "Ngerulmud", "Palau", "EAPR"),
    ("Pacific: Samoa: Apia", "Pacific", "Apia", "Samoa", "EAPR"),
    ("Pacific: Solomon Islands: Honiara", "Pacific", "Honiara", "Solomon Islands", "EAPR"),
    ("Pacific: Tokelau: Nukunonu", "Pacific", "Nukunonu", "Tokelau", "EAPR"),
    ("Pacific: Tonga: Nuku'alofa", "Pacific", "Nuku'alofa", "Tonga", "EAPR"),
    ("Pacific: Tuvalu: Funafuti", "Pacific", "Funafuti", "Tuvalu", "EAPR"),
    ("Pacific: Vanuatu: Port Vila", "Pacific", "Port Vila", "Vanuatu", "EAPR"),
    ("Pakistan: Islamabad", "N/A", "Islamabad", "Pakistan", "SAR"),
    ("Pakistan: Karachi", "N/A", "Karachi", "Pakistan", "SAR"),
    ("Pakistan: Lahore", "N/A", "Lahore", "Pakistan", "SAR"),
    ("Pakistan: Peshawar", "N/A", "Peshawar", "Pakistan", "SAR"),
    ("Pakistan: Quetta", "N/A", "Quetta", "Pakistan", "SAR"),
    ("Panama: Panama City", "N/A", "Panama City", "Panama", "LACR"),
    ("Papua New Guinea: Port Moresby", "N/A", "Port Moresby", "Papua New Guinea", "EAPR"),
    ("Paraguay: Asuncion", "N/A", "Asuncion", "Paraguay", "LACR"),
    ("Peru: Lima", "N/A", "Lima", "Peru", "LACR"),
    ("Philippines: Cotabato City", "N/A", "Cotabato City", "Philippines", "EAPR"),
    ("Philippines: Manila", "N/A", "Manila", "Philippines", "EAPR"),
    ("Philippines: Tacloban", "N/A", "Tacloban", "Philippines", "EAPR"),
    ("Republic Of Moldova: Chisinau", "N/A", "Chisinau", "Republic Of Moldova", "ECAR"),
    ("Romania: Bucharest", "N/A", "Bucharest", "Romania", "ECAR"),
    ("ROSA: Kathmandu", "ROSA", "Kathmandu", "Nepal", "SAR"),
    ("Rwanda: Kigali", "N/A", "Kigali", "Rwanda", "ESAR"),
    ("Sao Tome and Principe: Sao Tome", "N/A", "Sao Tome", "Sao Tome and Principe", "WCAR"),
    ("Senegal: Dakar", "N/A", "Dakar", "Senegal", "WCAR"),
    ("Senegal: Kolda", "N/A", "Kolda", "Senegal", "WCAR"),
    ("Serbia: Belgrade", "N/A", "Belgrade", "Serbia", "ECAR"),
    ("Sierra Leone: Freetown", "N/A", "Freetown", "Sierra Leone", "WCAR"),
    ("Sierra Leone: Kenema", "N/A", "Kenema", "Sierra Leone", "WCAR"),
    ("Sierra Leone: Makeni", "N/A", "Makeni", "Sierra Leone", "WCAR"),
    ("Somalia: Baidoa", "N/A", "Baidoa", "Somalia", "ESAR"),
    ("Somalia: Dolow", "N/A", "Dolow", "Somalia", "ESAR"),
    ("Somalia: Garowe", "N/A", "Garowe", "Somalia", "ESAR"),
    ("Somalia: Hargeisa", "N/A", "Hargeisa", "Somalia", "ESAR"),
    ("Somalia: Mogadishu", "N/A", "Mogadishu", "Somalia", "ESAR"),
    ("Somalia: Somalia Support Center (USSC): Nairobi", "Somalia Support Center (USSC)", "Nairobi", "Somalia", "ESAR"),
    ("South Africa: Pretoria", "N/A", "Pretoria", "South Africa", "ESAR"),
    ("South Sudan: Abyei", "N/A", "Abyei", "South Sudan", "ESAR"),
    ("South Sudan: Aweil", "N/A", "Aweil", "South Sudan", "ESAR"),
    ("South Sudan: Bentiu", "N/A", "Bentiu", "South Sudan", "ESAR"),
    ("South Sudan: Bor", "N/A", "Bor", "South Sudan", "ESAR"),
    ("South Sudan: Juba", "N/A", "Juba", "South Sudan", "ESAR"),
    ("South Sudan: Kuajok", "N/A", "Kuajok", "South Sudan", "ESAR"),
    ("South Sudan: Malakal", "N/A", "Malakal", "South Sudan", "ESAR"),
    ("South Sudan: Pibor", "N/A", "Pibor", "South Sudan", "ESAR"),
    ("South Sudan: Rumbek", "N/A", "Rumbek", "South Sudan", "ESAR"),
    ("South Sudan: Torit", "N/A", "Torit", "South Sudan", "ESAR"),
    ("South Sudan: Wau", "N/A", "Wau", "South Sudan", "ESAR"),
    ("South Sudan: Yambio", "N/A", "Yambio", "South Sudan", "ESAR"),
    ("South Sudan: Yei", "N/A", "Yei", "South Sudan", "ESAR"),
    ("Sri Lanka: Badulla", "N/A", "Badulla", "Sri Lanka", "SAR"),
    ("Sri Lanka: Batticaloa", "N/A", "Batticaloa", "Sri Lanka", "SAR"),
    ("Sri Lanka: Colombo", "N/A", "Colombo", "Sri Lanka", "SAR"),
    ("Sri Lanka: Kilinochi", "N/A", "Kilinochi", "Sri Lanka", "SAR"),
    ("Sri Lanka: Trincomalee", "N/A", "Trincomalee", "Sri Lanka", "SAR"),
    ("State of Palestine: East Jerusalem", "N/A", "East Jerusalem", "State of Palestine", "MENA"),
    ("State of Palestine: Gaza", "N/A", "Gaza", "State of Palestine", "MENA"),
    ("State of Palestine: Jerusalem", "N/A", "Jerusalem", "State of Palestine", "MENA"),
    ("Sudan: Damazine", "N/A", "Damazine", "Sudan", "MENA"),
    ("Sudan: Ed Da'ein", "N/A", "Ed Da'ein", "Sudan", "MENA"),
    ("Sudan: El Fasher", "N/A", "El Fasher", "Sudan", "MENA"),
    ("Sudan: El Geneina", "N/A", "El Geneina", "Sudan", "MENA"),
    ("Sudan: Kadugli", "N/A", "Kadugli", "Sudan", "MENA"),
    ("Sudan: Kassala", "N/A", "Kassala", "Sudan", "MENA"),
    ("Sudan: Khartoum", "N/A", "Khartoum", "Sudan", "MENA"),
    ("Sudan: Kosti", "N/A", "Kosti", "Sudan", "MENA"),
    ("Sudan: Nyala", "N/A", "Nyala", "Sudan", "MENA"),
    ("Sudan: Port Sudan", "N/A", "Port Sudan", "Sudan", "MENA"),
    ("Sudan: Zalingei", "N/A", "Zalingei", "Sudan", "MENA"),
    ("Suriname: Paramaribo", "N/A", "Paramaribo", "Suriname", "LACR"),
    ("Switzerland: Athens", "N/A", "Athens", "Switzerland", "ECAR"),
    ("Syrian Arab Republic: Aleppo", "N/A", "Aleppo", "Syrian Arab Republic", "MENA"),
    ("Syrian Arab Republic: Damascus", "N/A", "Damascus", "Syrian Arab Republic", "MENA"),
    ("Syrian Arab Republic: Homs", "N/A", "Homs", "Syrian Arab Republic", "MENA"),
    ("Syrian Arab Republic: Qamishli", "N/A", "Qamishli", "Syrian Arab Republic", "MENA"),
    ("Syrian Arab Republic: Tartus", "N/A", "Tartus", "Syrian Arab Republic", "MENA"),
    ("Tajikistan: Dushanbe", "N/A", "Dushanbe", "Tajikistan", "ECAR"),
    ("Tajikistan: Khujand", "N/A", "Khujand", "Tajikistan", "ECAR"),
    ("Thailand: Bangkok", "N/A", "Bangkok", "Thailand", "EAPR"),
    ("Timor-Leste: Dili", "N/A", "Dili", "Timor-Leste", "EAPR"),
    ("Togo: Lome", "N/A", "Lome", "Togo", "WCAR"),
    ("Tunisia: Tunis", "N/A", "Tunis", "Tunisia", "MENA"),
    ("Turkey: Ankara", "N/A", "Ankara", "Turkey", "ECAR"),
    ("Turkey: Gaziantep", "N/A", "Gaziantep", "Turkey", "ECAR"),
    ("Turkey: Istanbul", "N/A", "Istanbul", "Turkey", "ECAR"),
    ("Turkmenistan: Ashgabat", "N/A", "Ashgabat", "Turkmenistan", "ECAR"),
    ("Uganda: Gulu", "N/A", "Gulu", "Uganda", "ESAR"),
    ("Uganda: Kampala", "N/A", "Kampala", "Uganda", "ESAR"),
    ("Uganda: Mbarara", "N/A", "Mbarara", "Uganda", "ESAR"),
    ("Uganda: Moroto", "N/A", "Moroto", "Uganda", "ESAR"),
    ("Ukraine: Donetsk", "N/A", "Donetsk", "Ukraine", "ECAR"),
    ("Ukraine: Kiev", "N/A", "Kiev", "Ukraine", "ECAR"),
    ("Ukraine: Kramatorsk", "N/A", "Kramatorsk", "Ukraine", "ECAR"),
    ("Ukraine: Luhansk", "N/A", "Luhansk", "Ukraine", "ECAR"),
    ("Ukraine: Mariupol", "N/A", "Mariupol", "Ukraine", "ECAR"),
    ("United Republic of Tanzania: Dar-es-Salaam", "N/A", "Dar-es-Salaam", "United Republic of Tanzania", "ESAR"),
    ("United Republic of Tanzania: Dodoma", "N/A", "Dodoma", "United Republic of Tanzania", "ESAR"),
    ("United Republic of Tanzania: Kibondo", "N/A", "Kibondo", "United Republic of Tanzania", "ESAR"),
    ("United Republic of Tanzania: Mbeya", "N/A", "Mbeya", "United Republic of Tanzania", "ESAR"),
    ("United Republic of Tanzania: Zanzibar", "N/A", "Zanzibar", "United Republic of Tanzania", "ESAR"),
    ("Uruguay: Montevideo", "N/A", "Montevideo", "Uruguay", "LACR"),
    ("Uzbekistan: Tashkent", "N/A", "Tashkent", "Uzbekistan", "ECAR"),
    ("Venezuela (Bolivarian Republic of): Caracas", "N/A", "Caracas", "Venezuela (Bolivarian Republic of)", "LACR"),
    (
        "Venezuela (Bolivarian Republic of): Ciudad Guayana", "N/A", "Ciudad Guayana",
        "Venezuela (Bolivarian Republic of)",
        "LACR"),
    ("Viet Nam: Hanoi", "N/A", "Hanoi", "Viet Nam", "EAPR"),
    ("Viet Nam: Ho Chi Minh City", "N/A", "Ho Chi Minh City", "Viet Nam", "EAPR"),
    ("WCARO: Dakar", "WCARO", "Dakar", "Senegal", "WCAR"),
    ("Yemen: Aden", "N/A", "Aden", "Yemen", "MENA"),
    ("Yemen: Hodeidah", "N/A", "Hodeidah", "Yemen", "MENA"),
    ("Yemen: Ibb", "N/A", "Ibb", "Yemen", "MENA"),
    ("Yemen: Sa'dah", "N/A", "Sa'dah", "Yemen", "MENA"),
    ("Yemen: Sana'a", "N/A", "Sana'a", "Yemen", "MENA"),
    ("Yemen: Ta'izz", "N/A", "Ta'izz", "Yemen", "MENA"),
    ("Zambia: Lusaka", "N/A", "Lusaka", "Zambia", "ESAR"),
    ("Zimbabwe: Harare", "N/A", "Harare", "Zimbabwe", "ESAR")
]

ro = [
    'Gulf Area Office',
    'LACRO',
    'EAPRO',
    'New Zealand National Committee',
    'Australian National Committee',
    'Japan National Committee',
    'Korea National Committee',
    'MENARO',
    'Pacific',
    'Office for the Eastern Caribbean Area',
    'Somalia Support Center (USSC)',
    'WCARO',
    'ECARO',
    'N/A',
    'ESARO',
    'Hong Kong Committee',
    'Pacific Multi Country Office',
    'ROSA',
    'Eastern Carribean',
    'HQ'
]

countries_not_matched = {
    'Anguilla': 'AI',
    'Turks and Caicos Islands': 'TC',
    'China, Hong Kong Special Administrative Region': 'HK',
    'State of Palestine': 'PS',
    'Tokelau': 'TK',
    'Kosovo (UNSCR 1244/99)': 'XK',
    'Montserrat': 'MS',
    'British Virgin Islands': 'VG'
}
