{{- if not (eq .Values.environment "local") }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-{{ include "invent-django.fullname" . }}-keyvault
  labels:
    {{- include "invent-django.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.vault.clientID }}   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ .Values.vault.name }}        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: osm-map-cli-key-{{ .Values.environment }}
          objectType: secret
        - |
          objectName: secret-key-{{ .Values.environment }}
          objectType: secret
        - |
          objectName: uni-invent-{{ .Values.environment }}-secret
          objectType: secret
        - |
          objectName: uni-invent-{{ .Values.environment }}-id
          objectType: secret
        - |
          objectName: azure-tenant
          objectType: secret
        - |
          objectName: {{ .Values.envFullName }}-azure-postgres-password
          objectType: secret
    tenantId: {{ .Values.vault.tenantID }}
  secretObjects:
    - secretName: azure-{{ include "invent-django.fullname" . }}-keyvault
      data:
        - key: osm-map-cli-key-{{ .Values.environment }}
          objectName: osm-map-cli-key-{{ .Values.environment }}
        - key: secret-key-{{ .Values.environment }}
          objectName: secret-key-{{ .Values.environment }}
        - key: uni-invent-{{ .Values.environment }}-secret
          objectName: uni-invent-{{ .Values.environment }}-secret
        - key: uni-invent-{{ .Values.environment }}-id
          objectName: uni-invent-{{ .Values.environment }}-id
        - key: azure-tenant
          objectName: azure-tenant
        - key: {{ .Values.envFullName }}-azure-postgres-password
          objectName: {{ .Values.envFullName }}-azure-postgres-password
      type: Opaque
{{- end }}