# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20160601_0928'),
        ('user', '0003_auto_20160601_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation',
        ),
    ]
