# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20160601_0928'),
        ('user', '0004_remove_userprofile_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation_fk',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Organisation'),
            preserve_default=False,
        ),
    ]
