# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160601_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('I', 'Implementer'), ('D', 'Financial Investor'), ('G', 'Government')], default='I', max_length=1),
        ),
    ]
