# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160609_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('I', 'Implementer'), ('D', 'Financial Investor'), ('G', 'Government'), ('Y', 'Inventory User')], default='I', max_length=1),
        ),
    ]
