# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 14:57
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_country_admin_group(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, c = Group.objects.get_or_create(name='Country Admin')
    group.permissions.set([
        Permission.objects.get(codename='change_country'),
        Permission.objects.get(codename='add_partnerlogo'),
        Permission.objects.get(codename='change_partnerlogo'),
        Permission.objects.get(codename='delete_partnerlogo'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('user', '0008_auto_20160719_1259'),
        ('auth', '0008_alter_user_username_max_length'),
        ('country', '0017_remove_country_user'),
    ]

    operations = [
        migrations.RunPython(create_country_admin_group, migrations.RunPython.noop),
    ]
