# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_auto_20171211_1138'),
        ('user', '0012_auto_20171231_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country'),
        ),
    ]
