# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 16:53
from __future__ import unicode_literals

from django.db import migrations


def link_countries(apps, schema_editor):
    Country = apps.get_model('country', 'Country')
    UserProfile = apps.get_model('user', 'UserProfile')
    for profile in UserProfile.objects.all():
        try:
            country = Country.objects.get(name=profile.country)
        except Exception:
            continue
        profile.country_link = country
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_country_link'),
    ]

    operations = [
        migrations.RunPython(link_countries)
    ]
