# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_link_countries_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
