# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-03 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_userprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country_link',
            new_name='country',
        ),
    ]
