# Generated by Django 2.0.7 on 2018-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0035_auto_20180808_1256'),
        ('user', '0021_auto_20180815_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donor',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='country.Donor'),
        ),
    ]
