# Generated by Django 2.0.7 on 2018-08-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0035_auto_20180808_1256'),
        ('user', '0022_userprofile_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='donor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofiles', to='country.Donor'),
        ),
    ]
