# Generated by Django 2.1 on 2019-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190205_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('I', 'Implementer'), ('D', 'Investor Viewer'), ('DA', 'Investor Admin'), ('SDA', 'Investor System Admin'), ('G', 'Government Viewer'), ('CA', 'Government Admin'), ('SCA', 'Government System Admin'), ('Y', 'Inventory User')], default='I', max_length=3),
        ),
    ]
