# Generated by Django 2.1 on 2020-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190312_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_portfolio_owner',
            field=models.BooleanField(default=False),
        ),
    ]
