# Generated by Django 2.1 on 2020-11-09 12:49
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_global_portfolio_owner'),
    ]

    operations = [
        HStoreExtension()
    ]
