# Generated by Django 2.1 on 2020-11-09 13:01

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_add_hstore_postgres_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filters',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
