# Generated by Django 2.1 on 2021-09-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userprofile_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='odk_sync',
        ),
    ]
