# Generated by Django 2.1 on 2021-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0053_auto_20201105_1330'),
        ('user', '0029_remove_userprofile_odk_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_of',
            field=models.ManyToManyField(blank=True, related_name='country_managers', to='country.CountryOffice', verbose_name='Country Manager Of'),
        ),
    ]
