# Generated by Django 2.1 on 2022-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_userprofile_manager_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
    ]
