# Generated by Django 2.1 on 2023-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20230511_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LACR'), (4, 'MENA'), (5, 'SAR'), (6, 'WCAR'), (7, 'HQ')], null=True),
        ),
    ]
