# Generated by Django 2.1 on 2023-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'EAPR'), (1, 'ECAR'), (2, 'ESAR'), (3, 'LACR'), (4, 'MENA'), (5, 'SAR'), (6, 'WCAR'), (7, 'HQ')], null=True, verbose_name='Regional Focal point for'),
        ),
    ]
